/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the PRODUCTSDEFAULTLINKG type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PRODUCTSDEFAULTLINKG{}

// PRODUCTSDEFAULTLINKG struct for PRODUCTSDEFAULTLINKG
type PRODUCTSDEFAULTLINKG struct {
	ProductImage NullableString `json:"product_image,omitempty"`
	Link NullableString `json:"link,omitempty"`
	Code NullableString `json:"code,omitempty"`
	Serial NullableString `json:"serial,omitempty"`
	ProductId NullableString `json:"product_id,omitempty"`
	PriceId NullableString `json:"price_id,omitempty"`
	Value NullableInt64 `json:"value,omitempty"`
	ExpiredDate NullableString `json:"expired_date,omitempty"`
}

// NewPRODUCTSDEFAULTLINKG instantiates a new PRODUCTSDEFAULTLINKG object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPRODUCTSDEFAULTLINKG() *PRODUCTSDEFAULTLINKG {
	this := PRODUCTSDEFAULTLINKG{}
	return &this
}

// NewPRODUCTSDEFAULTLINKGWithDefaults instantiates a new PRODUCTSDEFAULTLINKG object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPRODUCTSDEFAULTLINKGWithDefaults() *PRODUCTSDEFAULTLINKG {
	this := PRODUCTSDEFAULTLINKG{}
	return &this
}

// GetProductImage returns the ProductImage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetProductImage() string {
	if o == nil || IsNil(o.ProductImage.Get()) {
		var ret string
		return ret
	}
	return *o.ProductImage.Get()
}

// GetProductImageOk returns a tuple with the ProductImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetProductImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductImage.Get(), o.ProductImage.IsSet()
}

// HasProductImage returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasProductImage() bool {
	if o != nil && o.ProductImage.IsSet() {
		return true
	}

	return false
}

// SetProductImage gets a reference to the given NullableString and assigns it to the ProductImage field.
func (o *PRODUCTSDEFAULTLINKG) SetProductImage(v string) {
	o.ProductImage.Set(&v)
}
// SetProductImageNil sets the value for ProductImage to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetProductImageNil() {
	o.ProductImage.Set(nil)
}

// UnsetProductImage ensures that no value is present for ProductImage, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetProductImage() {
	o.ProductImage.Unset()
}

// GetLink returns the Link field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetLink() string {
	if o == nil || IsNil(o.Link.Get()) {
		var ret string
		return ret
	}
	return *o.Link.Get()
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Link.Get(), o.Link.IsSet()
}

// HasLink returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasLink() bool {
	if o != nil && o.Link.IsSet() {
		return true
	}

	return false
}

// SetLink gets a reference to the given NullableString and assigns it to the Link field.
func (o *PRODUCTSDEFAULTLINKG) SetLink(v string) {
	o.Link.Set(&v)
}
// SetLinkNil sets the value for Link to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetLinkNil() {
	o.Link.Set(nil)
}

// UnsetLink ensures that no value is present for Link, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetLink() {
	o.Link.Unset()
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetCode() string {
	if o == nil || IsNil(o.Code.Get()) {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *PRODUCTSDEFAULTLINKG) SetCode(v string) {
	o.Code.Set(&v)
}
// SetCodeNil sets the value for Code to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetCode() {
	o.Code.Unset()
}

// GetSerial returns the Serial field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetSerial() string {
	if o == nil || IsNil(o.Serial.Get()) {
		var ret string
		return ret
	}
	return *o.Serial.Get()
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetSerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Serial.Get(), o.Serial.IsSet()
}

// HasSerial returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasSerial() bool {
	if o != nil && o.Serial.IsSet() {
		return true
	}

	return false
}

// SetSerial gets a reference to the given NullableString and assigns it to the Serial field.
func (o *PRODUCTSDEFAULTLINKG) SetSerial(v string) {
	o.Serial.Set(&v)
}
// SetSerialNil sets the value for Serial to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetSerialNil() {
	o.Serial.Set(nil)
}

// UnsetSerial ensures that no value is present for Serial, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetSerial() {
	o.Serial.Unset()
}

// GetProductId returns the ProductId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetProductId() string {
	if o == nil || IsNil(o.ProductId.Get()) {
		var ret string
		return ret
	}
	return *o.ProductId.Get()
}

// GetProductIdOk returns a tuple with the ProductId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductId.Get(), o.ProductId.IsSet()
}

// HasProductId returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasProductId() bool {
	if o != nil && o.ProductId.IsSet() {
		return true
	}

	return false
}

// SetProductId gets a reference to the given NullableString and assigns it to the ProductId field.
func (o *PRODUCTSDEFAULTLINKG) SetProductId(v string) {
	o.ProductId.Set(&v)
}
// SetProductIdNil sets the value for ProductId to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetProductIdNil() {
	o.ProductId.Set(nil)
}

// UnsetProductId ensures that no value is present for ProductId, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetProductId() {
	o.ProductId.Unset()
}

// GetPriceId returns the PriceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetPriceId() string {
	if o == nil || IsNil(o.PriceId.Get()) {
		var ret string
		return ret
	}
	return *o.PriceId.Get()
}

// GetPriceIdOk returns a tuple with the PriceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetPriceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PriceId.Get(), o.PriceId.IsSet()
}

// HasPriceId returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasPriceId() bool {
	if o != nil && o.PriceId.IsSet() {
		return true
	}

	return false
}

// SetPriceId gets a reference to the given NullableString and assigns it to the PriceId field.
func (o *PRODUCTSDEFAULTLINKG) SetPriceId(v string) {
	o.PriceId.Set(&v)
}
// SetPriceIdNil sets the value for PriceId to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetPriceIdNil() {
	o.PriceId.Set(nil)
}

// UnsetPriceId ensures that no value is present for PriceId, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetPriceId() {
	o.PriceId.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetValue() int64 {
	if o == nil || IsNil(o.Value.Get()) {
		var ret int64
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableInt64 and assigns it to the Value field.
func (o *PRODUCTSDEFAULTLINKG) SetValue(v int64) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetValue() {
	o.Value.Unset()
}

// GetExpiredDate returns the ExpiredDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PRODUCTSDEFAULTLINKG) GetExpiredDate() string {
	if o == nil || IsNil(o.ExpiredDate.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiredDate.Get()
}

// GetExpiredDateOk returns a tuple with the ExpiredDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PRODUCTSDEFAULTLINKG) GetExpiredDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiredDate.Get(), o.ExpiredDate.IsSet()
}

// HasExpiredDate returns a boolean if a field has been set.
func (o *PRODUCTSDEFAULTLINKG) HasExpiredDate() bool {
	if o != nil && o.ExpiredDate.IsSet() {
		return true
	}

	return false
}

// SetExpiredDate gets a reference to the given NullableString and assigns it to the ExpiredDate field.
func (o *PRODUCTSDEFAULTLINKG) SetExpiredDate(v string) {
	o.ExpiredDate.Set(&v)
}
// SetExpiredDateNil sets the value for ExpiredDate to be an explicit nil
func (o *PRODUCTSDEFAULTLINKG) SetExpiredDateNil() {
	o.ExpiredDate.Set(nil)
}

// UnsetExpiredDate ensures that no value is present for ExpiredDate, not even an explicit nil
func (o *PRODUCTSDEFAULTLINKG) UnsetExpiredDate() {
	o.ExpiredDate.Unset()
}

func (o PRODUCTSDEFAULTLINKG) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PRODUCTSDEFAULTLINKG) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProductImage.IsSet() {
		toSerialize["product_image"] = o.ProductImage.Get()
	}
	if o.Link.IsSet() {
		toSerialize["link"] = o.Link.Get()
	}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if o.Serial.IsSet() {
		toSerialize["serial"] = o.Serial.Get()
	}
	if o.ProductId.IsSet() {
		toSerialize["product_id"] = o.ProductId.Get()
	}
	if o.PriceId.IsSet() {
		toSerialize["price_id"] = o.PriceId.Get()
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if o.ExpiredDate.IsSet() {
		toSerialize["expired_date"] = o.ExpiredDate.Get()
	}
	return toSerialize, nil
}

type NullablePRODUCTSDEFAULTLINKG struct {
	value *PRODUCTSDEFAULTLINKG
	isSet bool
}

func (v NullablePRODUCTSDEFAULTLINKG) Get() *PRODUCTSDEFAULTLINKG {
	return v.value
}

func (v *NullablePRODUCTSDEFAULTLINKG) Set(val *PRODUCTSDEFAULTLINKG) {
	v.value = val
	v.isSet = true
}

func (v NullablePRODUCTSDEFAULTLINKG) IsSet() bool {
	return v.isSet
}

func (v *NullablePRODUCTSDEFAULTLINKG) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePRODUCTSDEFAULTLINKG(val *PRODUCTSDEFAULTLINKG) *NullablePRODUCTSDEFAULTLINKG {
	return &NullablePRODUCTSDEFAULTLINKG{value: val, isSet: true}
}

func (v NullablePRODUCTSDEFAULTLINKG) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePRODUCTSDEFAULTLINKG) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


