/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the REQUESTSENDVOUCHERBYZNS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &REQUESTSENDVOUCHERBYZNS{}

// REQUESTSENDVOUCHERBYZNS struct for REQUESTSENDVOUCHERBYZNS
type REQUESTSENDVOUCHERBYZNS struct {
	PhoneNo string `json:"phoneNo"`
	ReceiverNm *string `json:"receiverNm,omitempty"`
	VoucherSerials []string `json:"voucherSerials"`
	TransactionId string `json:"transactionId"`
}

type _REQUESTSENDVOUCHERBYZNS REQUESTSENDVOUCHERBYZNS

// NewREQUESTSENDVOUCHERBYZNS instantiates a new REQUESTSENDVOUCHERBYZNS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewREQUESTSENDVOUCHERBYZNS(phoneNo string, voucherSerials []string, transactionId string) *REQUESTSENDVOUCHERBYZNS {
	this := REQUESTSENDVOUCHERBYZNS{}
	this.PhoneNo = phoneNo
	this.VoucherSerials = voucherSerials
	this.TransactionId = transactionId
	return &this
}

// NewREQUESTSENDVOUCHERBYZNSWithDefaults instantiates a new REQUESTSENDVOUCHERBYZNS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewREQUESTSENDVOUCHERBYZNSWithDefaults() *REQUESTSENDVOUCHERBYZNS {
	this := REQUESTSENDVOUCHERBYZNS{}
	return &this
}

// GetPhoneNo returns the PhoneNo field value
func (o *REQUESTSENDVOUCHERBYZNS) GetPhoneNo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNo
}

// GetPhoneNoOk returns a tuple with the PhoneNo field value
// and a boolean to check if the value has been set.
func (o *REQUESTSENDVOUCHERBYZNS) GetPhoneNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNo, true
}

// SetPhoneNo sets field value
func (o *REQUESTSENDVOUCHERBYZNS) SetPhoneNo(v string) {
	o.PhoneNo = v
}

// GetReceiverNm returns the ReceiverNm field value if set, zero value otherwise.
func (o *REQUESTSENDVOUCHERBYZNS) GetReceiverNm() string {
	if o == nil || IsNil(o.ReceiverNm) {
		var ret string
		return ret
	}
	return *o.ReceiverNm
}

// GetReceiverNmOk returns a tuple with the ReceiverNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTSENDVOUCHERBYZNS) GetReceiverNmOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiverNm) {
		return nil, false
	}
	return o.ReceiverNm, true
}

// HasReceiverNm returns a boolean if a field has been set.
func (o *REQUESTSENDVOUCHERBYZNS) HasReceiverNm() bool {
	if o != nil && !IsNil(o.ReceiverNm) {
		return true
	}

	return false
}

// SetReceiverNm gets a reference to the given string and assigns it to the ReceiverNm field.
func (o *REQUESTSENDVOUCHERBYZNS) SetReceiverNm(v string) {
	o.ReceiverNm = &v
}

// GetVoucherSerials returns the VoucherSerials field value
func (o *REQUESTSENDVOUCHERBYZNS) GetVoucherSerials() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.VoucherSerials
}

// GetVoucherSerialsOk returns a tuple with the VoucherSerials field value
// and a boolean to check if the value has been set.
func (o *REQUESTSENDVOUCHERBYZNS) GetVoucherSerialsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherSerials, true
}

// SetVoucherSerials sets field value
func (o *REQUESTSENDVOUCHERBYZNS) SetVoucherSerials(v []string) {
	o.VoucherSerials = v
}

// GetTransactionId returns the TransactionId field value
func (o *REQUESTSENDVOUCHERBYZNS) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *REQUESTSENDVOUCHERBYZNS) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *REQUESTSENDVOUCHERBYZNS) SetTransactionId(v string) {
	o.TransactionId = v
}

func (o REQUESTSENDVOUCHERBYZNS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o REQUESTSENDVOUCHERBYZNS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phoneNo"] = o.PhoneNo
	if !IsNil(o.ReceiverNm) {
		toSerialize["receiverNm"] = o.ReceiverNm
	}
	toSerialize["voucherSerials"] = o.VoucherSerials
	toSerialize["transactionId"] = o.TransactionId
	return toSerialize, nil
}

func (o *REQUESTSENDVOUCHERBYZNS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phoneNo",
		"voucherSerials",
		"transactionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varREQUESTSENDVOUCHERBYZNS := _REQUESTSENDVOUCHERBYZNS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varREQUESTSENDVOUCHERBYZNS)

	if err != nil {
		return err
	}

	*o = REQUESTSENDVOUCHERBYZNS(varREQUESTSENDVOUCHERBYZNS)

	return err
}

type NullableREQUESTSENDVOUCHERBYZNS struct {
	value *REQUESTSENDVOUCHERBYZNS
	isSet bool
}

func (v NullableREQUESTSENDVOUCHERBYZNS) Get() *REQUESTSENDVOUCHERBYZNS {
	return v.value
}

func (v *NullableREQUESTSENDVOUCHERBYZNS) Set(val *REQUESTSENDVOUCHERBYZNS) {
	v.value = val
	v.isSet = true
}

func (v NullableREQUESTSENDVOUCHERBYZNS) IsSet() bool {
	return v.isSet
}

func (v *NullableREQUESTSENDVOUCHERBYZNS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableREQUESTSENDVOUCHERBYZNS(val *REQUESTSENDVOUCHERBYZNS) *NullableREQUESTSENDVOUCHERBYZNS {
	return &NullableREQUESTSENDVOUCHERBYZNS{value: val, isSet: true}
}

func (v NullableREQUESTSENDVOUCHERBYZNS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableREQUESTSENDVOUCHERBYZNS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


