/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// VOUCHERVSCHEMAProduct - struct for VOUCHERVSCHEMAProduct
type VOUCHERVSCHEMAProduct struct {
	PRODUCTV *PRODUCTV
}

// PRODUCTVAsVOUCHERVSCHEMAProduct is a convenience function that returns PRODUCTV wrapped in VOUCHERVSCHEMAProduct
func PRODUCTVAsVOUCHERVSCHEMAProduct(v *PRODUCTV) VOUCHERVSCHEMAProduct {
	return VOUCHERVSCHEMAProduct{
		PRODUCTV: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *VOUCHERVSCHEMAProduct) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into PRODUCTV
	err = newStrictDecoder(data).Decode(&dst.PRODUCTV)
	if err == nil {
		jsonPRODUCTV, _ := json.Marshal(dst.PRODUCTV)
		if string(jsonPRODUCTV) == "{}" { // empty struct
			dst.PRODUCTV = nil
		} else {
			if err = validator.Validate(dst.PRODUCTV); err != nil {
				dst.PRODUCTV = nil
			} else {
				match++
			}
		}
	} else {
		dst.PRODUCTV = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PRODUCTV = nil

		return fmt.Errorf("data matches more than one schema in oneOf(VOUCHERVSCHEMAProduct)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(VOUCHERVSCHEMAProduct)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src VOUCHERVSCHEMAProduct) MarshalJSON() ([]byte, error) {
	if src.PRODUCTV != nil {
		return json.Marshal(&src.PRODUCTV)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *VOUCHERVSCHEMAProduct) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PRODUCTV != nil {
		return obj.PRODUCTV
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj VOUCHERVSCHEMAProduct) GetActualInstanceValue() (interface{}) {
	if obj.PRODUCTV != nil {
		return *obj.PRODUCTV
	}

	// all schemas are nil
	return nil
}

type NullableVOUCHERVSCHEMAProduct struct {
	value *VOUCHERVSCHEMAProduct
	isSet bool
}

func (v NullableVOUCHERVSCHEMAProduct) Get() *VOUCHERVSCHEMAProduct {
	return v.value
}

func (v *NullableVOUCHERVSCHEMAProduct) Set(val *VOUCHERVSCHEMAProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERVSCHEMAProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERVSCHEMAProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERVSCHEMAProduct(val *VOUCHERVSCHEMAProduct) *NullableVOUCHERVSCHEMAProduct {
	return &NullableVOUCHERVSCHEMAProduct{value: val, isSet: true}
}

func (v NullableVOUCHERVSCHEMAProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERVSCHEMAProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


