/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the REQUESTCREATEVOUCHERLINKV type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &REQUESTCREATEVOUCHERLINKV{}

// REQUESTCREATEVOUCHERLINKV struct for REQUESTCREATEVOUCHERLINKV
type REQUESTCREATEVOUCHERLINKV struct {
	// Product id. You can see the Products section for the product id. Note: productId type auto convert merchant code does not support creating cover links.
	ProductId int64 `json:"productId"`
	// Product price id. Each product will have 1 or more denomination codes corresponding to the value or converted product size.
	ProductPriceId int64 `json:"productPriceId"`
	// Number of vouchers to be issued
	Quantity int64 `json:"quantity"`
	// Please don't use the voucher recipient or the content changes daily or frequently. Owl French: Customers specified name + [Month] + [Year] Example: Got It Promotion - Jul 2019
	OrderName string `json:"orderName"`
	// Voucher expiration date. Syntax 'YYYY-MM-DD'. The expiration date is specified specified in the contract between the partner and Got It, usually 3 months from the release date, maximum 12 months.
	ExpiryDate string `json:"expiryDate"`
	// Transaction code receive from the customer request, used for comparison and reconciliation. If the transaction fails, after 5 mintegerues, you can use this transmitted transactionRefID to request again. Maximum 255 characters. Format of transactionRefId: prefix + '_' + character string In which: + prefix: string of 06 integer characters provided by Got It. + character string: string actively generated by clients Example: prefix: '000742' character string: '20220126-6f823f2e' => transactionRefId: '000742_20220126-6f823f2e'
	TransactionRefId string `json:"transactionRefId"`
	// = 1 if the end user is required to enter a password to view the voucher. Example: 1
	UseOtp *int64 `json:"use_otp,omitempty"`
	// = 1 if OTP is sent via phone number; = 7 if OTP is sent via email; = 8 if password Password is a fixed number - passed in param 'password' For example: 1
	OtpType *int64 `json:"otp_type,omitempty"`
	// Fixed password (corresponding to otp_type=8 passed in parram 'otp_type'. For otp_type = 1 or 7 do not need to be passed integero this field). Format requirement: 6 consecutive integer characters Example: '325243'
	Password *string `json:"password,omitempty"`
	// Voucher recipient name Example: Son Tran
	ReceiverName *string `json:"receiver_name,omitempty"`
	// Phone number to receive the voucher. This is only the step to identify the phone number that will receive the voucher. This step has not been completed yet. Sending vouchers, sending vouchers via SMS will be a separate API section. This phone number is also used to receive OTP when the end-user opens the voucher link, respectively otp_type = 1. Request format: 10 consecutive integer characters. For example: 0909xxxxxx
	Phone *string `json:"phone,omitempty"`
	// Email to receive the voucher. This is just the step to identify the email address that will receive the voucher. This step does not include sending the voucher, sending the voucher via email will be a separate API section. This email address is also used to receive OTP when the end-user opens the voucher link, corresponding to otp_type = 7 . For example: son.tran@ dayone.vn
	Email *string `json:"email,omitempty"`
	// RSA encryption, used for client authentication
	Signature *string `json:"signature,omitempty"`
	// Voucher validity start date, validity date must be greater than issue date. Format: 'YYYY-MM-DD'. Note: before this date, the voucher will be in Inactive status and cannot be used.
	ActiveDate *string `json:"activeDate,omitempty"`
	// Type of voucher link to be issued: If = 0 (default): Create voucher link. If = 1: Create cover link for voucher link.
	IsConvertToCoverLink *int64 `json:"isConvertToCoverLink,omitempty"`
}

type _REQUESTCREATEVOUCHERLINKV REQUESTCREATEVOUCHERLINKV

// NewREQUESTCREATEVOUCHERLINKV instantiates a new REQUESTCREATEVOUCHERLINKV object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewREQUESTCREATEVOUCHERLINKV(productId int64, productPriceId int64, quantity int64, orderName string, expiryDate string, transactionRefId string) *REQUESTCREATEVOUCHERLINKV {
	this := REQUESTCREATEVOUCHERLINKV{}
	this.ProductId = productId
	this.ProductPriceId = productPriceId
	this.Quantity = quantity
	this.OrderName = orderName
	this.ExpiryDate = expiryDate
	this.TransactionRefId = transactionRefId
	return &this
}

// NewREQUESTCREATEVOUCHERLINKVWithDefaults instantiates a new REQUESTCREATEVOUCHERLINKV object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewREQUESTCREATEVOUCHERLINKVWithDefaults() *REQUESTCREATEVOUCHERLINKV {
	this := REQUESTCREATEVOUCHERLINKV{}
	return &this
}

// GetProductId returns the ProductId field value
func (o *REQUESTCREATEVOUCHERLINKV) GetProductId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetProductIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *REQUESTCREATEVOUCHERLINKV) SetProductId(v int64) {
	o.ProductId = v
}

// GetProductPriceId returns the ProductPriceId field value
func (o *REQUESTCREATEVOUCHERLINKV) GetProductPriceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ProductPriceId
}

// GetProductPriceIdOk returns a tuple with the ProductPriceId field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetProductPriceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductPriceId, true
}

// SetProductPriceId sets field value
func (o *REQUESTCREATEVOUCHERLINKV) SetProductPriceId(v int64) {
	o.ProductPriceId = v
}

// GetQuantity returns the Quantity field value
func (o *REQUESTCREATEVOUCHERLINKV) GetQuantity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetQuantityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *REQUESTCREATEVOUCHERLINKV) SetQuantity(v int64) {
	o.Quantity = v
}

// GetOrderName returns the OrderName field value
func (o *REQUESTCREATEVOUCHERLINKV) GetOrderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderName
}

// GetOrderNameOk returns a tuple with the OrderName field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetOrderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderName, true
}

// SetOrderName sets field value
func (o *REQUESTCREATEVOUCHERLINKV) SetOrderName(v string) {
	o.OrderName = v
}

// GetExpiryDate returns the ExpiryDate field value
func (o *REQUESTCREATEVOUCHERLINKV) GetExpiryDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetExpiryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiryDate, true
}

// SetExpiryDate sets field value
func (o *REQUESTCREATEVOUCHERLINKV) SetExpiryDate(v string) {
	o.ExpiryDate = v
}

// GetTransactionRefId returns the TransactionRefId field value
func (o *REQUESTCREATEVOUCHERLINKV) GetTransactionRefId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionRefId
}

// GetTransactionRefIdOk returns a tuple with the TransactionRefId field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetTransactionRefIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionRefId, true
}

// SetTransactionRefId sets field value
func (o *REQUESTCREATEVOUCHERLINKV) SetTransactionRefId(v string) {
	o.TransactionRefId = v
}

// GetUseOtp returns the UseOtp field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetUseOtp() int64 {
	if o == nil || IsNil(o.UseOtp) {
		var ret int64
		return ret
	}
	return *o.UseOtp
}

// GetUseOtpOk returns a tuple with the UseOtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetUseOtpOk() (*int64, bool) {
	if o == nil || IsNil(o.UseOtp) {
		return nil, false
	}
	return o.UseOtp, true
}

// HasUseOtp returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasUseOtp() bool {
	if o != nil && !IsNil(o.UseOtp) {
		return true
	}

	return false
}

// SetUseOtp gets a reference to the given int64 and assigns it to the UseOtp field.
func (o *REQUESTCREATEVOUCHERLINKV) SetUseOtp(v int64) {
	o.UseOtp = &v
}

// GetOtpType returns the OtpType field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetOtpType() int64 {
	if o == nil || IsNil(o.OtpType) {
		var ret int64
		return ret
	}
	return *o.OtpType
}

// GetOtpTypeOk returns a tuple with the OtpType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetOtpTypeOk() (*int64, bool) {
	if o == nil || IsNil(o.OtpType) {
		return nil, false
	}
	return o.OtpType, true
}

// HasOtpType returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasOtpType() bool {
	if o != nil && !IsNil(o.OtpType) {
		return true
	}

	return false
}

// SetOtpType gets a reference to the given int64 and assigns it to the OtpType field.
func (o *REQUESTCREATEVOUCHERLINKV) SetOtpType(v int64) {
	o.OtpType = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *REQUESTCREATEVOUCHERLINKV) SetPassword(v string) {
	o.Password = &v
}

// GetReceiverName returns the ReceiverName field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetReceiverName() string {
	if o == nil || IsNil(o.ReceiverName) {
		var ret string
		return ret
	}
	return *o.ReceiverName
}

// GetReceiverNameOk returns a tuple with the ReceiverName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetReceiverNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiverName) {
		return nil, false
	}
	return o.ReceiverName, true
}

// HasReceiverName returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasReceiverName() bool {
	if o != nil && !IsNil(o.ReceiverName) {
		return true
	}

	return false
}

// SetReceiverName gets a reference to the given string and assigns it to the ReceiverName field.
func (o *REQUESTCREATEVOUCHERLINKV) SetReceiverName(v string) {
	o.ReceiverName = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *REQUESTCREATEVOUCHERLINKV) SetPhone(v string) {
	o.Phone = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *REQUESTCREATEVOUCHERLINKV) SetEmail(v string) {
	o.Email = &v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetSignature() string {
	if o == nil || IsNil(o.Signature) {
		var ret string
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetSignatureOk() (*string, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given string and assigns it to the Signature field.
func (o *REQUESTCREATEVOUCHERLINKV) SetSignature(v string) {
	o.Signature = &v
}

// GetActiveDate returns the ActiveDate field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetActiveDate() string {
	if o == nil || IsNil(o.ActiveDate) {
		var ret string
		return ret
	}
	return *o.ActiveDate
}

// GetActiveDateOk returns a tuple with the ActiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetActiveDateOk() (*string, bool) {
	if o == nil || IsNil(o.ActiveDate) {
		return nil, false
	}
	return o.ActiveDate, true
}

// HasActiveDate returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasActiveDate() bool {
	if o != nil && !IsNil(o.ActiveDate) {
		return true
	}

	return false
}

// SetActiveDate gets a reference to the given string and assigns it to the ActiveDate field.
func (o *REQUESTCREATEVOUCHERLINKV) SetActiveDate(v string) {
	o.ActiveDate = &v
}

// GetIsConvertToCoverLink returns the IsConvertToCoverLink field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKV) GetIsConvertToCoverLink() int64 {
	if o == nil || IsNil(o.IsConvertToCoverLink) {
		var ret int64
		return ret
	}
	return *o.IsConvertToCoverLink
}

// GetIsConvertToCoverLinkOk returns a tuple with the IsConvertToCoverLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKV) GetIsConvertToCoverLinkOk() (*int64, bool) {
	if o == nil || IsNil(o.IsConvertToCoverLink) {
		return nil, false
	}
	return o.IsConvertToCoverLink, true
}

// HasIsConvertToCoverLink returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKV) HasIsConvertToCoverLink() bool {
	if o != nil && !IsNil(o.IsConvertToCoverLink) {
		return true
	}

	return false
}

// SetIsConvertToCoverLink gets a reference to the given int64 and assigns it to the IsConvertToCoverLink field.
func (o *REQUESTCREATEVOUCHERLINKV) SetIsConvertToCoverLink(v int64) {
	o.IsConvertToCoverLink = &v
}

func (o REQUESTCREATEVOUCHERLINKV) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o REQUESTCREATEVOUCHERLINKV) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["productId"] = o.ProductId
	toSerialize["productPriceId"] = o.ProductPriceId
	toSerialize["quantity"] = o.Quantity
	toSerialize["orderName"] = o.OrderName
	toSerialize["expiryDate"] = o.ExpiryDate
	toSerialize["transactionRefId"] = o.TransactionRefId
	if !IsNil(o.UseOtp) {
		toSerialize["use_otp"] = o.UseOtp
	}
	if !IsNil(o.OtpType) {
		toSerialize["otp_type"] = o.OtpType
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.ReceiverName) {
		toSerialize["receiver_name"] = o.ReceiverName
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	if !IsNil(o.ActiveDate) {
		toSerialize["activeDate"] = o.ActiveDate
	}
	if !IsNil(o.IsConvertToCoverLink) {
		toSerialize["isConvertToCoverLink"] = o.IsConvertToCoverLink
	}
	return toSerialize, nil
}

func (o *REQUESTCREATEVOUCHERLINKV) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productId",
		"productPriceId",
		"quantity",
		"orderName",
		"expiryDate",
		"transactionRefId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varREQUESTCREATEVOUCHERLINKV := _REQUESTCREATEVOUCHERLINKV{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varREQUESTCREATEVOUCHERLINKV)

	if err != nil {
		return err
	}

	*o = REQUESTCREATEVOUCHERLINKV(varREQUESTCREATEVOUCHERLINKV)

	return err
}

type NullableREQUESTCREATEVOUCHERLINKV struct {
	value *REQUESTCREATEVOUCHERLINKV
	isSet bool
}

func (v NullableREQUESTCREATEVOUCHERLINKV) Get() *REQUESTCREATEVOUCHERLINKV {
	return v.value
}

func (v *NullableREQUESTCREATEVOUCHERLINKV) Set(val *REQUESTCREATEVOUCHERLINKV) {
	v.value = val
	v.isSet = true
}

func (v NullableREQUESTCREATEVOUCHERLINKV) IsSet() bool {
	return v.isSet
}

func (v *NullableREQUESTCREATEVOUCHERLINKV) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableREQUESTCREATEVOUCHERLINKV(val *REQUESTCREATEVOUCHERLINKV) *NullableREQUESTCREATEVOUCHERLINKV {
	return &NullableREQUESTCREATEVOUCHERLINKV{value: val, isSet: true}
}

func (v NullableREQUESTCREATEVOUCHERLINKV) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableREQUESTCREATEVOUCHERLINKV) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


