/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the VOUCHERSENDSMSSCHEMA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VOUCHERSENDSMSSCHEMA{}

// VOUCHERSENDSMSSCHEMA struct for VOUCHERSENDSMSSCHEMA
type VOUCHERSENDSMSSCHEMA struct {
	// Last 8 characters of voucher link
	VoucherLinkCode NullableString `json:"voucherLinkCode,omitempty"`
	// Phone of user receive voucher
	PhoneNo NullableString `json:"phoneNo,omitempty"`
	// Email of user receive voucher
	ReceiverNm NullableString `json:"receiverNm,omitempty"`
	// Name of sender
	SenderNm NullableString `json:"senderNm,omitempty"`
}

// NewVOUCHERSENDSMSSCHEMA instantiates a new VOUCHERSENDSMSSCHEMA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVOUCHERSENDSMSSCHEMA() *VOUCHERSENDSMSSCHEMA {
	this := VOUCHERSENDSMSSCHEMA{}
	return &this
}

// NewVOUCHERSENDSMSSCHEMAWithDefaults instantiates a new VOUCHERSENDSMSSCHEMA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVOUCHERSENDSMSSCHEMAWithDefaults() *VOUCHERSENDSMSSCHEMA {
	this := VOUCHERSENDSMSSCHEMA{}
	return &this
}

// GetVoucherLinkCode returns the VoucherLinkCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDSMSSCHEMA) GetVoucherLinkCode() string {
	if o == nil || IsNil(o.VoucherLinkCode.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherLinkCode.Get()
}

// GetVoucherLinkCodeOk returns a tuple with the VoucherLinkCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDSMSSCHEMA) GetVoucherLinkCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherLinkCode.Get(), o.VoucherLinkCode.IsSet()
}

// HasVoucherLinkCode returns a boolean if a field has been set.
func (o *VOUCHERSENDSMSSCHEMA) HasVoucherLinkCode() bool {
	if o != nil && o.VoucherLinkCode.IsSet() {
		return true
	}

	return false
}

// SetVoucherLinkCode gets a reference to the given NullableString and assigns it to the VoucherLinkCode field.
func (o *VOUCHERSENDSMSSCHEMA) SetVoucherLinkCode(v string) {
	o.VoucherLinkCode.Set(&v)
}
// SetVoucherLinkCodeNil sets the value for VoucherLinkCode to be an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) SetVoucherLinkCodeNil() {
	o.VoucherLinkCode.Set(nil)
}

// UnsetVoucherLinkCode ensures that no value is present for VoucherLinkCode, not even an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) UnsetVoucherLinkCode() {
	o.VoucherLinkCode.Unset()
}

// GetPhoneNo returns the PhoneNo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDSMSSCHEMA) GetPhoneNo() string {
	if o == nil || IsNil(o.PhoneNo.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNo.Get()
}

// GetPhoneNoOk returns a tuple with the PhoneNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDSMSSCHEMA) GetPhoneNoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNo.Get(), o.PhoneNo.IsSet()
}

// HasPhoneNo returns a boolean if a field has been set.
func (o *VOUCHERSENDSMSSCHEMA) HasPhoneNo() bool {
	if o != nil && o.PhoneNo.IsSet() {
		return true
	}

	return false
}

// SetPhoneNo gets a reference to the given NullableString and assigns it to the PhoneNo field.
func (o *VOUCHERSENDSMSSCHEMA) SetPhoneNo(v string) {
	o.PhoneNo.Set(&v)
}
// SetPhoneNoNil sets the value for PhoneNo to be an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) SetPhoneNoNil() {
	o.PhoneNo.Set(nil)
}

// UnsetPhoneNo ensures that no value is present for PhoneNo, not even an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) UnsetPhoneNo() {
	o.PhoneNo.Unset()
}

// GetReceiverNm returns the ReceiverNm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDSMSSCHEMA) GetReceiverNm() string {
	if o == nil || IsNil(o.ReceiverNm.Get()) {
		var ret string
		return ret
	}
	return *o.ReceiverNm.Get()
}

// GetReceiverNmOk returns a tuple with the ReceiverNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDSMSSCHEMA) GetReceiverNmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceiverNm.Get(), o.ReceiverNm.IsSet()
}

// HasReceiverNm returns a boolean if a field has been set.
func (o *VOUCHERSENDSMSSCHEMA) HasReceiverNm() bool {
	if o != nil && o.ReceiverNm.IsSet() {
		return true
	}

	return false
}

// SetReceiverNm gets a reference to the given NullableString and assigns it to the ReceiverNm field.
func (o *VOUCHERSENDSMSSCHEMA) SetReceiverNm(v string) {
	o.ReceiverNm.Set(&v)
}
// SetReceiverNmNil sets the value for ReceiverNm to be an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) SetReceiverNmNil() {
	o.ReceiverNm.Set(nil)
}

// UnsetReceiverNm ensures that no value is present for ReceiverNm, not even an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) UnsetReceiverNm() {
	o.ReceiverNm.Unset()
}

// GetSenderNm returns the SenderNm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDSMSSCHEMA) GetSenderNm() string {
	if o == nil || IsNil(o.SenderNm.Get()) {
		var ret string
		return ret
	}
	return *o.SenderNm.Get()
}

// GetSenderNmOk returns a tuple with the SenderNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDSMSSCHEMA) GetSenderNmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SenderNm.Get(), o.SenderNm.IsSet()
}

// HasSenderNm returns a boolean if a field has been set.
func (o *VOUCHERSENDSMSSCHEMA) HasSenderNm() bool {
	if o != nil && o.SenderNm.IsSet() {
		return true
	}

	return false
}

// SetSenderNm gets a reference to the given NullableString and assigns it to the SenderNm field.
func (o *VOUCHERSENDSMSSCHEMA) SetSenderNm(v string) {
	o.SenderNm.Set(&v)
}
// SetSenderNmNil sets the value for SenderNm to be an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) SetSenderNmNil() {
	o.SenderNm.Set(nil)
}

// UnsetSenderNm ensures that no value is present for SenderNm, not even an explicit nil
func (o *VOUCHERSENDSMSSCHEMA) UnsetSenderNm() {
	o.SenderNm.Unset()
}

func (o VOUCHERSENDSMSSCHEMA) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VOUCHERSENDSMSSCHEMA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.VoucherLinkCode.IsSet() {
		toSerialize["voucherLinkCode"] = o.VoucherLinkCode.Get()
	}
	if o.PhoneNo.IsSet() {
		toSerialize["phoneNo"] = o.PhoneNo.Get()
	}
	if o.ReceiverNm.IsSet() {
		toSerialize["receiverNm"] = o.ReceiverNm.Get()
	}
	if o.SenderNm.IsSet() {
		toSerialize["senderNm"] = o.SenderNm.Get()
	}
	return toSerialize, nil
}

type NullableVOUCHERSENDSMSSCHEMA struct {
	value *VOUCHERSENDSMSSCHEMA
	isSet bool
}

func (v NullableVOUCHERSENDSMSSCHEMA) Get() *VOUCHERSENDSMSSCHEMA {
	return v.value
}

func (v *NullableVOUCHERSENDSMSSCHEMA) Set(val *VOUCHERSENDSMSSCHEMA) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERSENDSMSSCHEMA) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERSENDSMSSCHEMA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERSENDSMSSCHEMA(val *VOUCHERSENDSMSSCHEMA) *NullableVOUCHERSENDSMSSCHEMA {
	return &NullableVOUCHERSENDSMSSCHEMA{value: val, isSet: true}
}

func (v NullableVOUCHERSENDSMSSCHEMA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERSENDSMSSCHEMA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


