/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the VOUCHERGSCHEMA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VOUCHERGSCHEMA{}

// VOUCHERGSCHEMA struct for VOUCHERGSCHEMA
type VOUCHERGSCHEMA struct {
	// Order Id
	OrderId NullableInt64 `json:"orderId,omitempty"`
	// Order name from client request
	OrderName NullableString `json:"orderName,omitempty"`
	GroupVouchers *GROUPVOUCHERSCHEMA `json:"groupVouchers,omitempty"`
	Vouchers []PRODUCTG `json:"vouchers,omitempty"`
}

// NewVOUCHERGSCHEMA instantiates a new VOUCHERGSCHEMA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVOUCHERGSCHEMA() *VOUCHERGSCHEMA {
	this := VOUCHERGSCHEMA{}
	return &this
}

// NewVOUCHERGSCHEMAWithDefaults instantiates a new VOUCHERGSCHEMA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVOUCHERGSCHEMAWithDefaults() *VOUCHERGSCHEMA {
	this := VOUCHERGSCHEMA{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERGSCHEMA) GetOrderId() int64 {
	if o == nil || IsNil(o.OrderId.Get()) {
		var ret int64
		return ret
	}
	return *o.OrderId.Get()
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERGSCHEMA) GetOrderIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderId.Get(), o.OrderId.IsSet()
}

// HasOrderId returns a boolean if a field has been set.
func (o *VOUCHERGSCHEMA) HasOrderId() bool {
	if o != nil && o.OrderId.IsSet() {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given NullableInt64 and assigns it to the OrderId field.
func (o *VOUCHERGSCHEMA) SetOrderId(v int64) {
	o.OrderId.Set(&v)
}
// SetOrderIdNil sets the value for OrderId to be an explicit nil
func (o *VOUCHERGSCHEMA) SetOrderIdNil() {
	o.OrderId.Set(nil)
}

// UnsetOrderId ensures that no value is present for OrderId, not even an explicit nil
func (o *VOUCHERGSCHEMA) UnsetOrderId() {
	o.OrderId.Unset()
}

// GetOrderName returns the OrderName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERGSCHEMA) GetOrderName() string {
	if o == nil || IsNil(o.OrderName.Get()) {
		var ret string
		return ret
	}
	return *o.OrderName.Get()
}

// GetOrderNameOk returns a tuple with the OrderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERGSCHEMA) GetOrderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderName.Get(), o.OrderName.IsSet()
}

// HasOrderName returns a boolean if a field has been set.
func (o *VOUCHERGSCHEMA) HasOrderName() bool {
	if o != nil && o.OrderName.IsSet() {
		return true
	}

	return false
}

// SetOrderName gets a reference to the given NullableString and assigns it to the OrderName field.
func (o *VOUCHERGSCHEMA) SetOrderName(v string) {
	o.OrderName.Set(&v)
}
// SetOrderNameNil sets the value for OrderName to be an explicit nil
func (o *VOUCHERGSCHEMA) SetOrderNameNil() {
	o.OrderName.Set(nil)
}

// UnsetOrderName ensures that no value is present for OrderName, not even an explicit nil
func (o *VOUCHERGSCHEMA) UnsetOrderName() {
	o.OrderName.Unset()
}

// GetGroupVouchers returns the GroupVouchers field value if set, zero value otherwise.
func (o *VOUCHERGSCHEMA) GetGroupVouchers() GROUPVOUCHERSCHEMA {
	if o == nil || IsNil(o.GroupVouchers) {
		var ret GROUPVOUCHERSCHEMA
		return ret
	}
	return *o.GroupVouchers
}

// GetGroupVouchersOk returns a tuple with the GroupVouchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VOUCHERGSCHEMA) GetGroupVouchersOk() (*GROUPVOUCHERSCHEMA, bool) {
	if o == nil || IsNil(o.GroupVouchers) {
		return nil, false
	}
	return o.GroupVouchers, true
}

// HasGroupVouchers returns a boolean if a field has been set.
func (o *VOUCHERGSCHEMA) HasGroupVouchers() bool {
	if o != nil && !IsNil(o.GroupVouchers) {
		return true
	}

	return false
}

// SetGroupVouchers gets a reference to the given GROUPVOUCHERSCHEMA and assigns it to the GroupVouchers field.
func (o *VOUCHERGSCHEMA) SetGroupVouchers(v GROUPVOUCHERSCHEMA) {
	o.GroupVouchers = &v
}

// GetVouchers returns the Vouchers field value if set, zero value otherwise.
func (o *VOUCHERGSCHEMA) GetVouchers() []PRODUCTG {
	if o == nil || IsNil(o.Vouchers) {
		var ret []PRODUCTG
		return ret
	}
	return o.Vouchers
}

// GetVouchersOk returns a tuple with the Vouchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VOUCHERGSCHEMA) GetVouchersOk() ([]PRODUCTG, bool) {
	if o == nil || IsNil(o.Vouchers) {
		return nil, false
	}
	return o.Vouchers, true
}

// HasVouchers returns a boolean if a field has been set.
func (o *VOUCHERGSCHEMA) HasVouchers() bool {
	if o != nil && !IsNil(o.Vouchers) {
		return true
	}

	return false
}

// SetVouchers gets a reference to the given []PRODUCTG and assigns it to the Vouchers field.
func (o *VOUCHERGSCHEMA) SetVouchers(v []PRODUCTG) {
	o.Vouchers = v
}

func (o VOUCHERGSCHEMA) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VOUCHERGSCHEMA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderId.IsSet() {
		toSerialize["orderId"] = o.OrderId.Get()
	}
	if o.OrderName.IsSet() {
		toSerialize["orderName"] = o.OrderName.Get()
	}
	if !IsNil(o.GroupVouchers) {
		toSerialize["groupVouchers"] = o.GroupVouchers
	}
	if !IsNil(o.Vouchers) {
		toSerialize["vouchers"] = o.Vouchers
	}
	return toSerialize, nil
}

type NullableVOUCHERGSCHEMA struct {
	value *VOUCHERGSCHEMA
	isSet bool
}

func (v NullableVOUCHERGSCHEMA) Get() *VOUCHERGSCHEMA {
	return v.value
}

func (v *NullableVOUCHERGSCHEMA) Set(val *VOUCHERGSCHEMA) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERGSCHEMA) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERGSCHEMA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERGSCHEMA(val *VOUCHERGSCHEMA) *NullableVOUCHERGSCHEMA {
	return &NullableVOUCHERGSCHEMA{value: val, isSet: true}
}

func (v NullableVOUCHERGSCHEMA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERGSCHEMA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


