/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the GROUPVOUCHERSCHEMA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GROUPVOUCHERSCHEMA{}

// GROUPVOUCHERSCHEMA struct for GROUPVOUCHERSCHEMA
type GROUPVOUCHERSCHEMA struct {
	// Link of voucher
	VoucherLink NullableString `json:"voucherLink,omitempty"`
	// Last 8 characters of voucher link
	VoucherLinkCode NullableString `json:"voucherLinkCode,omitempty"`
	// Is a unique code to identify voucher link v and is not valid for use. For example: V1562342ET2
	VoucherSerial NullableString `json:"voucherSerial,omitempty"`
}

// NewGROUPVOUCHERSCHEMA instantiates a new GROUPVOUCHERSCHEMA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGROUPVOUCHERSCHEMA() *GROUPVOUCHERSCHEMA {
	this := GROUPVOUCHERSCHEMA{}
	return &this
}

// NewGROUPVOUCHERSCHEMAWithDefaults instantiates a new GROUPVOUCHERSCHEMA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGROUPVOUCHERSCHEMAWithDefaults() *GROUPVOUCHERSCHEMA {
	this := GROUPVOUCHERSCHEMA{}
	return &this
}

// GetVoucherLink returns the VoucherLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GROUPVOUCHERSCHEMA) GetVoucherLink() string {
	if o == nil || IsNil(o.VoucherLink.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherLink.Get()
}

// GetVoucherLinkOk returns a tuple with the VoucherLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GROUPVOUCHERSCHEMA) GetVoucherLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherLink.Get(), o.VoucherLink.IsSet()
}

// HasVoucherLink returns a boolean if a field has been set.
func (o *GROUPVOUCHERSCHEMA) HasVoucherLink() bool {
	if o != nil && o.VoucherLink.IsSet() {
		return true
	}

	return false
}

// SetVoucherLink gets a reference to the given NullableString and assigns it to the VoucherLink field.
func (o *GROUPVOUCHERSCHEMA) SetVoucherLink(v string) {
	o.VoucherLink.Set(&v)
}
// SetVoucherLinkNil sets the value for VoucherLink to be an explicit nil
func (o *GROUPVOUCHERSCHEMA) SetVoucherLinkNil() {
	o.VoucherLink.Set(nil)
}

// UnsetVoucherLink ensures that no value is present for VoucherLink, not even an explicit nil
func (o *GROUPVOUCHERSCHEMA) UnsetVoucherLink() {
	o.VoucherLink.Unset()
}

// GetVoucherLinkCode returns the VoucherLinkCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GROUPVOUCHERSCHEMA) GetVoucherLinkCode() string {
	if o == nil || IsNil(o.VoucherLinkCode.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherLinkCode.Get()
}

// GetVoucherLinkCodeOk returns a tuple with the VoucherLinkCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GROUPVOUCHERSCHEMA) GetVoucherLinkCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherLinkCode.Get(), o.VoucherLinkCode.IsSet()
}

// HasVoucherLinkCode returns a boolean if a field has been set.
func (o *GROUPVOUCHERSCHEMA) HasVoucherLinkCode() bool {
	if o != nil && o.VoucherLinkCode.IsSet() {
		return true
	}

	return false
}

// SetVoucherLinkCode gets a reference to the given NullableString and assigns it to the VoucherLinkCode field.
func (o *GROUPVOUCHERSCHEMA) SetVoucherLinkCode(v string) {
	o.VoucherLinkCode.Set(&v)
}
// SetVoucherLinkCodeNil sets the value for VoucherLinkCode to be an explicit nil
func (o *GROUPVOUCHERSCHEMA) SetVoucherLinkCodeNil() {
	o.VoucherLinkCode.Set(nil)
}

// UnsetVoucherLinkCode ensures that no value is present for VoucherLinkCode, not even an explicit nil
func (o *GROUPVOUCHERSCHEMA) UnsetVoucherLinkCode() {
	o.VoucherLinkCode.Unset()
}

// GetVoucherSerial returns the VoucherSerial field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GROUPVOUCHERSCHEMA) GetVoucherSerial() string {
	if o == nil || IsNil(o.VoucherSerial.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherSerial.Get()
}

// GetVoucherSerialOk returns a tuple with the VoucherSerial field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GROUPVOUCHERSCHEMA) GetVoucherSerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherSerial.Get(), o.VoucherSerial.IsSet()
}

// HasVoucherSerial returns a boolean if a field has been set.
func (o *GROUPVOUCHERSCHEMA) HasVoucherSerial() bool {
	if o != nil && o.VoucherSerial.IsSet() {
		return true
	}

	return false
}

// SetVoucherSerial gets a reference to the given NullableString and assigns it to the VoucherSerial field.
func (o *GROUPVOUCHERSCHEMA) SetVoucherSerial(v string) {
	o.VoucherSerial.Set(&v)
}
// SetVoucherSerialNil sets the value for VoucherSerial to be an explicit nil
func (o *GROUPVOUCHERSCHEMA) SetVoucherSerialNil() {
	o.VoucherSerial.Set(nil)
}

// UnsetVoucherSerial ensures that no value is present for VoucherSerial, not even an explicit nil
func (o *GROUPVOUCHERSCHEMA) UnsetVoucherSerial() {
	o.VoucherSerial.Unset()
}

func (o GROUPVOUCHERSCHEMA) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GROUPVOUCHERSCHEMA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.VoucherLink.IsSet() {
		toSerialize["voucherLink"] = o.VoucherLink.Get()
	}
	if o.VoucherLinkCode.IsSet() {
		toSerialize["voucherLinkCode"] = o.VoucherLinkCode.Get()
	}
	if o.VoucherSerial.IsSet() {
		toSerialize["voucherSerial"] = o.VoucherSerial.Get()
	}
	return toSerialize, nil
}

type NullableGROUPVOUCHERSCHEMA struct {
	value *GROUPVOUCHERSCHEMA
	isSet bool
}

func (v NullableGROUPVOUCHERSCHEMA) Get() *GROUPVOUCHERSCHEMA {
	return v.value
}

func (v *NullableGROUPVOUCHERSCHEMA) Set(val *GROUPVOUCHERSCHEMA) {
	v.value = val
	v.isSet = true
}

func (v NullableGROUPVOUCHERSCHEMA) IsSet() bool {
	return v.isSet
}

func (v *NullableGROUPVOUCHERSCHEMA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGROUPVOUCHERSCHEMA(val *GROUPVOUCHERSCHEMA) *NullableGROUPVOUCHERSCHEMA {
	return &NullableGROUPVOUCHERSCHEMA{value: val, isSet: true}
}

func (v NullableGROUPVOUCHERSCHEMA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGROUPVOUCHERSCHEMA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


