/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the REQUESTCREATEVOUCHERLINKG type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &REQUESTCREATEVOUCHERLINKG{}

// REQUESTCREATEVOUCHERLINKG struct for REQUESTCREATEVOUCHERLINKG
type REQUESTCREATEVOUCHERLINKG struct {
	ProductList []PRODUCTDEFAULTLINKG `json:"productList"`
	// Please don't use the voucher recipient or the content changes daily or frequently. Owl French: Customers specified name + [Month] + [Year] Example: Got It Promotion - Jul 2019
	OrderName string `json:"orderName"`
	// Voucher expiration date. Syntax 'YYYY-MM-DD'. The expiration date is specified specified in the contract between the partner and Got It, usually 3 months from the release date, maximum 12 months.
	ExpiryDate string `json:"expiryDate"`
	// Transaction code receive from the customer request, used for comparison and reconciliation. If the transaction fails, after 5 mintegerues, you can use this transmitted transactionRefID to request again. Maximum 255 characters. Format of transactionRefId: prefix + '_' + character string In which: + prefix: string of 06 integer characters provided by Got It. + character string: string actively generated by clients Example: prefix: '000742' character string: '20220126-6f823f2e' => transactionRefId: '000742_20220126-6f823f2e'
	TransactionRefId string `json:"transactionRefId"`
	// = 1 if the end user is required to enter a password to view the voucher. Example: 1
	UseOtp *int64 `json:"use_otp,omitempty"`
	// = 1 if OTP is sent via phone number; = 7 if OTP is sent via email; = 8 if password Password is a fixed number - passed in param 'password' For example: 1
	OtpType *int64 `json:"otp_type,omitempty"`
	// Fixed password (corresponding to otp_type=8 passed in parram 'otp_type'. For otp_type = 1 or 7 do not need to be passed integero this field). Format requirement: 6 consecutive integer characters Example: '325243'
	Password *string `json:"password,omitempty"`
	// Voucher recipient name Example: Son Tran
	ReceiverName *string `json:"receiver_name,omitempty"`
	// Phone number to receive the voucher. This is only the step to identify the phone number that will receive the voucher. This step has not been completed yet. Sending vouchers, sending vouchers via SMS will be a separate API section. This phone number is also used to receive OTP when the end-user opens the voucher link, respectively otp_type = 1. Request format: 10 consecutive integer characters. For example: 0909xxxxxx
	Phone *string `json:"phone,omitempty"`
	// Email to receive the voucher. This is just the step to identify the email address that will receive the voucher. This step does not include sending the voucher, sending the voucher via email will be a separate API section. This email address is also used to receive OTP when the end-user opens the voucher link, corresponding to otp_type = 7 . For example: son.tran@ dayone.vn
	Email *string `json:"email,omitempty"`
}

type _REQUESTCREATEVOUCHERLINKG REQUESTCREATEVOUCHERLINKG

// NewREQUESTCREATEVOUCHERLINKG instantiates a new REQUESTCREATEVOUCHERLINKG object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewREQUESTCREATEVOUCHERLINKG(productList []PRODUCTDEFAULTLINKG, orderName string, expiryDate string, transactionRefId string) *REQUESTCREATEVOUCHERLINKG {
	this := REQUESTCREATEVOUCHERLINKG{}
	this.ProductList = productList
	this.OrderName = orderName
	this.ExpiryDate = expiryDate
	this.TransactionRefId = transactionRefId
	return &this
}

// NewREQUESTCREATEVOUCHERLINKGWithDefaults instantiates a new REQUESTCREATEVOUCHERLINKG object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewREQUESTCREATEVOUCHERLINKGWithDefaults() *REQUESTCREATEVOUCHERLINKG {
	this := REQUESTCREATEVOUCHERLINKG{}
	return &this
}

// GetProductList returns the ProductList field value
func (o *REQUESTCREATEVOUCHERLINKG) GetProductList() []PRODUCTDEFAULTLINKG {
	if o == nil {
		var ret []PRODUCTDEFAULTLINKG
		return ret
	}

	return o.ProductList
}

// GetProductListOk returns a tuple with the ProductList field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetProductListOk() ([]PRODUCTDEFAULTLINKG, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductList, true
}

// SetProductList sets field value
func (o *REQUESTCREATEVOUCHERLINKG) SetProductList(v []PRODUCTDEFAULTLINKG) {
	o.ProductList = v
}

// GetOrderName returns the OrderName field value
func (o *REQUESTCREATEVOUCHERLINKG) GetOrderName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderName
}

// GetOrderNameOk returns a tuple with the OrderName field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetOrderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderName, true
}

// SetOrderName sets field value
func (o *REQUESTCREATEVOUCHERLINKG) SetOrderName(v string) {
	o.OrderName = v
}

// GetExpiryDate returns the ExpiryDate field value
func (o *REQUESTCREATEVOUCHERLINKG) GetExpiryDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiryDate
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetExpiryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiryDate, true
}

// SetExpiryDate sets field value
func (o *REQUESTCREATEVOUCHERLINKG) SetExpiryDate(v string) {
	o.ExpiryDate = v
}

// GetTransactionRefId returns the TransactionRefId field value
func (o *REQUESTCREATEVOUCHERLINKG) GetTransactionRefId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionRefId
}

// GetTransactionRefIdOk returns a tuple with the TransactionRefId field value
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetTransactionRefIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionRefId, true
}

// SetTransactionRefId sets field value
func (o *REQUESTCREATEVOUCHERLINKG) SetTransactionRefId(v string) {
	o.TransactionRefId = v
}

// GetUseOtp returns the UseOtp field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKG) GetUseOtp() int64 {
	if o == nil || IsNil(o.UseOtp) {
		var ret int64
		return ret
	}
	return *o.UseOtp
}

// GetUseOtpOk returns a tuple with the UseOtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetUseOtpOk() (*int64, bool) {
	if o == nil || IsNil(o.UseOtp) {
		return nil, false
	}
	return o.UseOtp, true
}

// HasUseOtp returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKG) HasUseOtp() bool {
	if o != nil && !IsNil(o.UseOtp) {
		return true
	}

	return false
}

// SetUseOtp gets a reference to the given int64 and assigns it to the UseOtp field.
func (o *REQUESTCREATEVOUCHERLINKG) SetUseOtp(v int64) {
	o.UseOtp = &v
}

// GetOtpType returns the OtpType field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKG) GetOtpType() int64 {
	if o == nil || IsNil(o.OtpType) {
		var ret int64
		return ret
	}
	return *o.OtpType
}

// GetOtpTypeOk returns a tuple with the OtpType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetOtpTypeOk() (*int64, bool) {
	if o == nil || IsNil(o.OtpType) {
		return nil, false
	}
	return o.OtpType, true
}

// HasOtpType returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKG) HasOtpType() bool {
	if o != nil && !IsNil(o.OtpType) {
		return true
	}

	return false
}

// SetOtpType gets a reference to the given int64 and assigns it to the OtpType field.
func (o *REQUESTCREATEVOUCHERLINKG) SetOtpType(v int64) {
	o.OtpType = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKG) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKG) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *REQUESTCREATEVOUCHERLINKG) SetPassword(v string) {
	o.Password = &v
}

// GetReceiverName returns the ReceiverName field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKG) GetReceiverName() string {
	if o == nil || IsNil(o.ReceiverName) {
		var ret string
		return ret
	}
	return *o.ReceiverName
}

// GetReceiverNameOk returns a tuple with the ReceiverName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetReceiverNameOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiverName) {
		return nil, false
	}
	return o.ReceiverName, true
}

// HasReceiverName returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKG) HasReceiverName() bool {
	if o != nil && !IsNil(o.ReceiverName) {
		return true
	}

	return false
}

// SetReceiverName gets a reference to the given string and assigns it to the ReceiverName field.
func (o *REQUESTCREATEVOUCHERLINKG) SetReceiverName(v string) {
	o.ReceiverName = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKG) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKG) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *REQUESTCREATEVOUCHERLINKG) SetPhone(v string) {
	o.Phone = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *REQUESTCREATEVOUCHERLINKG) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *REQUESTCREATEVOUCHERLINKG) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *REQUESTCREATEVOUCHERLINKG) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *REQUESTCREATEVOUCHERLINKG) SetEmail(v string) {
	o.Email = &v
}

func (o REQUESTCREATEVOUCHERLINKG) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o REQUESTCREATEVOUCHERLINKG) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["productList"] = o.ProductList
	toSerialize["orderName"] = o.OrderName
	toSerialize["expiryDate"] = o.ExpiryDate
	toSerialize["transactionRefId"] = o.TransactionRefId
	if !IsNil(o.UseOtp) {
		toSerialize["use_otp"] = o.UseOtp
	}
	if !IsNil(o.OtpType) {
		toSerialize["otp_type"] = o.OtpType
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.ReceiverName) {
		toSerialize["receiver_name"] = o.ReceiverName
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

func (o *REQUESTCREATEVOUCHERLINKG) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productList",
		"orderName",
		"expiryDate",
		"transactionRefId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varREQUESTCREATEVOUCHERLINKG := _REQUESTCREATEVOUCHERLINKG{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varREQUESTCREATEVOUCHERLINKG)

	if err != nil {
		return err
	}

	*o = REQUESTCREATEVOUCHERLINKG(varREQUESTCREATEVOUCHERLINKG)

	return err
}

type NullableREQUESTCREATEVOUCHERLINKG struct {
	value *REQUESTCREATEVOUCHERLINKG
	isSet bool
}

func (v NullableREQUESTCREATEVOUCHERLINKG) Get() *REQUESTCREATEVOUCHERLINKG {
	return v.value
}

func (v *NullableREQUESTCREATEVOUCHERLINKG) Set(val *REQUESTCREATEVOUCHERLINKG) {
	v.value = val
	v.isSet = true
}

func (v NullableREQUESTCREATEVOUCHERLINKG) IsSet() bool {
	return v.isSet
}

func (v *NullableREQUESTCREATEVOUCHERLINKG) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableREQUESTCREATEVOUCHERLINKG(val *REQUESTCREATEVOUCHERLINKG) *NullableREQUESTCREATEVOUCHERLINKG {
	return &NullableREQUESTCREATEVOUCHERLINKG{value: val, isSet: true}
}

func (v NullableREQUESTCREATEVOUCHERLINKG) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableREQUESTCREATEVOUCHERLINKG) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


