/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the VOUCHERV type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VOUCHERV{}

// VOUCHERV struct for VOUCHERV
type VOUCHERV struct {
	// Order name from client request
	OrderName NullableString `json:"orderName,omitempty"`
	Vouchers []VOUCHERVSCHEMA `json:"vouchers,omitempty"`
}

// NewVOUCHERV instantiates a new VOUCHERV object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVOUCHERV() *VOUCHERV {
	this := VOUCHERV{}
	return &this
}

// NewVOUCHERVWithDefaults instantiates a new VOUCHERV object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVOUCHERVWithDefaults() *VOUCHERV {
	this := VOUCHERV{}
	return &this
}

// GetOrderName returns the OrderName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERV) GetOrderName() string {
	if o == nil || IsNil(o.OrderName.Get()) {
		var ret string
		return ret
	}
	return *o.OrderName.Get()
}

// GetOrderNameOk returns a tuple with the OrderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERV) GetOrderNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderName.Get(), o.OrderName.IsSet()
}

// HasOrderName returns a boolean if a field has been set.
func (o *VOUCHERV) HasOrderName() bool {
	if o != nil && o.OrderName.IsSet() {
		return true
	}

	return false
}

// SetOrderName gets a reference to the given NullableString and assigns it to the OrderName field.
func (o *VOUCHERV) SetOrderName(v string) {
	o.OrderName.Set(&v)
}
// SetOrderNameNil sets the value for OrderName to be an explicit nil
func (o *VOUCHERV) SetOrderNameNil() {
	o.OrderName.Set(nil)
}

// UnsetOrderName ensures that no value is present for OrderName, not even an explicit nil
func (o *VOUCHERV) UnsetOrderName() {
	o.OrderName.Unset()
}

// GetVouchers returns the Vouchers field value if set, zero value otherwise.
func (o *VOUCHERV) GetVouchers() []VOUCHERVSCHEMA {
	if o == nil || IsNil(o.Vouchers) {
		var ret []VOUCHERVSCHEMA
		return ret
	}
	return o.Vouchers
}

// GetVouchersOk returns a tuple with the Vouchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VOUCHERV) GetVouchersOk() ([]VOUCHERVSCHEMA, bool) {
	if o == nil || IsNil(o.Vouchers) {
		return nil, false
	}
	return o.Vouchers, true
}

// HasVouchers returns a boolean if a field has been set.
func (o *VOUCHERV) HasVouchers() bool {
	if o != nil && !IsNil(o.Vouchers) {
		return true
	}

	return false
}

// SetVouchers gets a reference to the given []VOUCHERVSCHEMA and assigns it to the Vouchers field.
func (o *VOUCHERV) SetVouchers(v []VOUCHERVSCHEMA) {
	o.Vouchers = v
}

func (o VOUCHERV) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VOUCHERV) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.OrderName.IsSet() {
		toSerialize["orderName"] = o.OrderName.Get()
	}
	if !IsNil(o.Vouchers) {
		toSerialize["vouchers"] = o.Vouchers
	}
	return toSerialize, nil
}

type NullableVOUCHERV struct {
	value *VOUCHERV
	isSet bool
}

func (v NullableVOUCHERV) Get() *VOUCHERV {
	return v.value
}

func (v *NullableVOUCHERV) Set(val *VOUCHERV) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERV) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERV) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERV(val *VOUCHERV) *NullableVOUCHERV {
	return &NullableVOUCHERV{value: val, isSet: true}
}

func (v NullableVOUCHERV) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERV) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


