/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the VOUCHERE type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VOUCHERE{}

// VOUCHERE struct for VOUCHERE
type VOUCHERE struct {
	// TransactionRefId receive from client request
	TransactionRefId NullableString `json:"transactionRefId,omitempty"`
	Vouchers []VOUCHERESCHEMA `json:"vouchers,omitempty"`
}

// NewVOUCHERE instantiates a new VOUCHERE object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVOUCHERE() *VOUCHERE {
	this := VOUCHERE{}
	return &this
}

// NewVOUCHEREWithDefaults instantiates a new VOUCHERE object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVOUCHEREWithDefaults() *VOUCHERE {
	this := VOUCHERE{}
	return &this
}

// GetTransactionRefId returns the TransactionRefId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERE) GetTransactionRefId() string {
	if o == nil || IsNil(o.TransactionRefId.Get()) {
		var ret string
		return ret
	}
	return *o.TransactionRefId.Get()
}

// GetTransactionRefIdOk returns a tuple with the TransactionRefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERE) GetTransactionRefIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionRefId.Get(), o.TransactionRefId.IsSet()
}

// HasTransactionRefId returns a boolean if a field has been set.
func (o *VOUCHERE) HasTransactionRefId() bool {
	if o != nil && o.TransactionRefId.IsSet() {
		return true
	}

	return false
}

// SetTransactionRefId gets a reference to the given NullableString and assigns it to the TransactionRefId field.
func (o *VOUCHERE) SetTransactionRefId(v string) {
	o.TransactionRefId.Set(&v)
}
// SetTransactionRefIdNil sets the value for TransactionRefId to be an explicit nil
func (o *VOUCHERE) SetTransactionRefIdNil() {
	o.TransactionRefId.Set(nil)
}

// UnsetTransactionRefId ensures that no value is present for TransactionRefId, not even an explicit nil
func (o *VOUCHERE) UnsetTransactionRefId() {
	o.TransactionRefId.Unset()
}

// GetVouchers returns the Vouchers field value if set, zero value otherwise.
func (o *VOUCHERE) GetVouchers() []VOUCHERESCHEMA {
	if o == nil || IsNil(o.Vouchers) {
		var ret []VOUCHERESCHEMA
		return ret
	}
	return o.Vouchers
}

// GetVouchersOk returns a tuple with the Vouchers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VOUCHERE) GetVouchersOk() ([]VOUCHERESCHEMA, bool) {
	if o == nil || IsNil(o.Vouchers) {
		return nil, false
	}
	return o.Vouchers, true
}

// HasVouchers returns a boolean if a field has been set.
func (o *VOUCHERE) HasVouchers() bool {
	if o != nil && !IsNil(o.Vouchers) {
		return true
	}

	return false
}

// SetVouchers gets a reference to the given []VOUCHERESCHEMA and assigns it to the Vouchers field.
func (o *VOUCHERE) SetVouchers(v []VOUCHERESCHEMA) {
	o.Vouchers = v
}

func (o VOUCHERE) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VOUCHERE) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TransactionRefId.IsSet() {
		toSerialize["transactionRefId"] = o.TransactionRefId.Get()
	}
	if !IsNil(o.Vouchers) {
		toSerialize["vouchers"] = o.Vouchers
	}
	return toSerialize, nil
}

type NullableVOUCHERE struct {
	value *VOUCHERE
	isSet bool
}

func (v NullableVOUCHERE) Get() *VOUCHERE {
	return v.value
}

func (v *NullableVOUCHERE) Set(val *VOUCHERE) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERE) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERE) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERE(val *VOUCHERE) *NullableVOUCHERE {
	return &NullableVOUCHERE{value: val, isSet: true}
}

func (v NullableVOUCHERE) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERE) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


