/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the STORESRESPONSEDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &STORESRESPONSEDataInner{}

// STORESRESPONSEDataInner struct for STORESRESPONSEDataInner
type STORESRESPONSEDataInner struct {
	StoreList []STORESSCHEMA `json:"storeList,omitempty"`
}

// NewSTORESRESPONSEDataInner instantiates a new STORESRESPONSEDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSTORESRESPONSEDataInner() *STORESRESPONSEDataInner {
	this := STORESRESPONSEDataInner{}
	return &this
}

// NewSTORESRESPONSEDataInnerWithDefaults instantiates a new STORESRESPONSEDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSTORESRESPONSEDataInnerWithDefaults() *STORESRESPONSEDataInner {
	this := STORESRESPONSEDataInner{}
	return &this
}

// GetStoreList returns the StoreList field value if set, zero value otherwise.
func (o *STORESRESPONSEDataInner) GetStoreList() []STORESSCHEMA {
	if o == nil || IsNil(o.StoreList) {
		var ret []STORESSCHEMA
		return ret
	}
	return o.StoreList
}

// GetStoreListOk returns a tuple with the StoreList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *STORESRESPONSEDataInner) GetStoreListOk() ([]STORESSCHEMA, bool) {
	if o == nil || IsNil(o.StoreList) {
		return nil, false
	}
	return o.StoreList, true
}

// HasStoreList returns a boolean if a field has been set.
func (o *STORESRESPONSEDataInner) HasStoreList() bool {
	if o != nil && !IsNil(o.StoreList) {
		return true
	}

	return false
}

// SetStoreList gets a reference to the given []STORESSCHEMA and assigns it to the StoreList field.
func (o *STORESRESPONSEDataInner) SetStoreList(v []STORESSCHEMA) {
	o.StoreList = v
}

func (o STORESRESPONSEDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o STORESRESPONSEDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StoreList) {
		toSerialize["storeList"] = o.StoreList
	}
	return toSerialize, nil
}

type NullableSTORESRESPONSEDataInner struct {
	value *STORESRESPONSEDataInner
	isSet bool
}

func (v NullableSTORESRESPONSEDataInner) Get() *STORESRESPONSEDataInner {
	return v.value
}

func (v *NullableSTORESRESPONSEDataInner) Set(val *STORESRESPONSEDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSTORESRESPONSEDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSTORESRESPONSEDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSTORESRESPONSEDataInner(val *STORESRESPONSEDataInner) *NullableSTORESRESPONSEDataInner {
	return &NullableSTORESRESPONSEDataInner{value: val, isSet: true}
}

func (v NullableSTORESRESPONSEDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSTORESRESPONSEDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


