/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the BRANDDETAIL type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BRANDDETAIL{}

// BRANDDETAIL struct for BRANDDETAIL
type BRANDDETAIL struct {
	// Brand id
	BrandId NullableInt64 `json:"brandId,omitempty"`
	// Brand name
	BrandNm NullableString `json:"brandNm,omitempty"`
	// Address of brand
	BrandAddr NullableString `json:"brandAddr,omitempty"`
	// Link to brand logo image
	BrandLogo NullableString `json:"brandLogo,omitempty"`
	// Brand name used for URL
	Slug *string `json:"slug,omitempty"`
	// Brand short description
	ShortDesc NullableString `json:"shortDesc,omitempty"`
	// Brand description
	Description NullableString `json:"description,omitempty"`
	// Array containing a list of Categories codes to which the Brand belongs
	CategoryID []interface{} `json:"categoryID,omitempty"`
	// The serial number displays the brand
	Order NullableInt64 `json:"order,omitempty"`
	// Describe the brand's terms of reference (T&C). HTML format
	ServiceGuide NullableString `json:"serviceGuide,omitempty"`
	Stores []STORESSCHEMA `json:"stores,omitempty"`
	// Information on the brand's applicable channels
	UsageMethods []USAGEMETHODSCHEMA `json:"usageMethods,omitempty"`
}

// NewBRANDDETAIL instantiates a new BRANDDETAIL object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBRANDDETAIL() *BRANDDETAIL {
	this := BRANDDETAIL{}
	return &this
}

// NewBRANDDETAILWithDefaults instantiates a new BRANDDETAIL object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBRANDDETAILWithDefaults() *BRANDDETAIL {
	this := BRANDDETAIL{}
	return &this
}

// GetBrandId returns the BrandId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetBrandId() int64 {
	if o == nil || IsNil(o.BrandId.Get()) {
		var ret int64
		return ret
	}
	return *o.BrandId.Get()
}

// GetBrandIdOk returns a tuple with the BrandId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetBrandIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandId.Get(), o.BrandId.IsSet()
}

// HasBrandId returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasBrandId() bool {
	if o != nil && o.BrandId.IsSet() {
		return true
	}

	return false
}

// SetBrandId gets a reference to the given NullableInt64 and assigns it to the BrandId field.
func (o *BRANDDETAIL) SetBrandId(v int64) {
	o.BrandId.Set(&v)
}
// SetBrandIdNil sets the value for BrandId to be an explicit nil
func (o *BRANDDETAIL) SetBrandIdNil() {
	o.BrandId.Set(nil)
}

// UnsetBrandId ensures that no value is present for BrandId, not even an explicit nil
func (o *BRANDDETAIL) UnsetBrandId() {
	o.BrandId.Unset()
}

// GetBrandNm returns the BrandNm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetBrandNm() string {
	if o == nil || IsNil(o.BrandNm.Get()) {
		var ret string
		return ret
	}
	return *o.BrandNm.Get()
}

// GetBrandNmOk returns a tuple with the BrandNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetBrandNmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandNm.Get(), o.BrandNm.IsSet()
}

// HasBrandNm returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasBrandNm() bool {
	if o != nil && o.BrandNm.IsSet() {
		return true
	}

	return false
}

// SetBrandNm gets a reference to the given NullableString and assigns it to the BrandNm field.
func (o *BRANDDETAIL) SetBrandNm(v string) {
	o.BrandNm.Set(&v)
}
// SetBrandNmNil sets the value for BrandNm to be an explicit nil
func (o *BRANDDETAIL) SetBrandNmNil() {
	o.BrandNm.Set(nil)
}

// UnsetBrandNm ensures that no value is present for BrandNm, not even an explicit nil
func (o *BRANDDETAIL) UnsetBrandNm() {
	o.BrandNm.Unset()
}

// GetBrandAddr returns the BrandAddr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetBrandAddr() string {
	if o == nil || IsNil(o.BrandAddr.Get()) {
		var ret string
		return ret
	}
	return *o.BrandAddr.Get()
}

// GetBrandAddrOk returns a tuple with the BrandAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetBrandAddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandAddr.Get(), o.BrandAddr.IsSet()
}

// HasBrandAddr returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasBrandAddr() bool {
	if o != nil && o.BrandAddr.IsSet() {
		return true
	}

	return false
}

// SetBrandAddr gets a reference to the given NullableString and assigns it to the BrandAddr field.
func (o *BRANDDETAIL) SetBrandAddr(v string) {
	o.BrandAddr.Set(&v)
}
// SetBrandAddrNil sets the value for BrandAddr to be an explicit nil
func (o *BRANDDETAIL) SetBrandAddrNil() {
	o.BrandAddr.Set(nil)
}

// UnsetBrandAddr ensures that no value is present for BrandAddr, not even an explicit nil
func (o *BRANDDETAIL) UnsetBrandAddr() {
	o.BrandAddr.Unset()
}

// GetBrandLogo returns the BrandLogo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetBrandLogo() string {
	if o == nil || IsNil(o.BrandLogo.Get()) {
		var ret string
		return ret
	}
	return *o.BrandLogo.Get()
}

// GetBrandLogoOk returns a tuple with the BrandLogo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetBrandLogoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandLogo.Get(), o.BrandLogo.IsSet()
}

// HasBrandLogo returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasBrandLogo() bool {
	if o != nil && o.BrandLogo.IsSet() {
		return true
	}

	return false
}

// SetBrandLogo gets a reference to the given NullableString and assigns it to the BrandLogo field.
func (o *BRANDDETAIL) SetBrandLogo(v string) {
	o.BrandLogo.Set(&v)
}
// SetBrandLogoNil sets the value for BrandLogo to be an explicit nil
func (o *BRANDDETAIL) SetBrandLogoNil() {
	o.BrandLogo.Set(nil)
}

// UnsetBrandLogo ensures that no value is present for BrandLogo, not even an explicit nil
func (o *BRANDDETAIL) UnsetBrandLogo() {
	o.BrandLogo.Unset()
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *BRANDDETAIL) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BRANDDETAIL) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *BRANDDETAIL) SetSlug(v string) {
	o.Slug = &v
}

// GetShortDesc returns the ShortDesc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetShortDesc() string {
	if o == nil || IsNil(o.ShortDesc.Get()) {
		var ret string
		return ret
	}
	return *o.ShortDesc.Get()
}

// GetShortDescOk returns a tuple with the ShortDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetShortDescOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShortDesc.Get(), o.ShortDesc.IsSet()
}

// HasShortDesc returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasShortDesc() bool {
	if o != nil && o.ShortDesc.IsSet() {
		return true
	}

	return false
}

// SetShortDesc gets a reference to the given NullableString and assigns it to the ShortDesc field.
func (o *BRANDDETAIL) SetShortDesc(v string) {
	o.ShortDesc.Set(&v)
}
// SetShortDescNil sets the value for ShortDesc to be an explicit nil
func (o *BRANDDETAIL) SetShortDescNil() {
	o.ShortDesc.Set(nil)
}

// UnsetShortDesc ensures that no value is present for ShortDesc, not even an explicit nil
func (o *BRANDDETAIL) UnsetShortDesc() {
	o.ShortDesc.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *BRANDDETAIL) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *BRANDDETAIL) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *BRANDDETAIL) UnsetDescription() {
	o.Description.Unset()
}

// GetCategoryID returns the CategoryID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetCategoryID() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}
	return o.CategoryID
}

// GetCategoryIDOk returns a tuple with the CategoryID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetCategoryIDOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.CategoryID) {
		return nil, false
	}
	return o.CategoryID, true
}

// HasCategoryID returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasCategoryID() bool {
	if o != nil && !IsNil(o.CategoryID) {
		return true
	}

	return false
}

// SetCategoryID gets a reference to the given []interface{} and assigns it to the CategoryID field.
func (o *BRANDDETAIL) SetCategoryID(v []interface{}) {
	o.CategoryID = v
}

// GetOrder returns the Order field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetOrder() int64 {
	if o == nil || IsNil(o.Order.Get()) {
		var ret int64
		return ret
	}
	return *o.Order.Get()
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetOrderOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Order.Get(), o.Order.IsSet()
}

// HasOrder returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasOrder() bool {
	if o != nil && o.Order.IsSet() {
		return true
	}

	return false
}

// SetOrder gets a reference to the given NullableInt64 and assigns it to the Order field.
func (o *BRANDDETAIL) SetOrder(v int64) {
	o.Order.Set(&v)
}
// SetOrderNil sets the value for Order to be an explicit nil
func (o *BRANDDETAIL) SetOrderNil() {
	o.Order.Set(nil)
}

// UnsetOrder ensures that no value is present for Order, not even an explicit nil
func (o *BRANDDETAIL) UnsetOrder() {
	o.Order.Unset()
}

// GetServiceGuide returns the ServiceGuide field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BRANDDETAIL) GetServiceGuide() string {
	if o == nil || IsNil(o.ServiceGuide.Get()) {
		var ret string
		return ret
	}
	return *o.ServiceGuide.Get()
}

// GetServiceGuideOk returns a tuple with the ServiceGuide field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BRANDDETAIL) GetServiceGuideOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServiceGuide.Get(), o.ServiceGuide.IsSet()
}

// HasServiceGuide returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasServiceGuide() bool {
	if o != nil && o.ServiceGuide.IsSet() {
		return true
	}

	return false
}

// SetServiceGuide gets a reference to the given NullableString and assigns it to the ServiceGuide field.
func (o *BRANDDETAIL) SetServiceGuide(v string) {
	o.ServiceGuide.Set(&v)
}
// SetServiceGuideNil sets the value for ServiceGuide to be an explicit nil
func (o *BRANDDETAIL) SetServiceGuideNil() {
	o.ServiceGuide.Set(nil)
}

// UnsetServiceGuide ensures that no value is present for ServiceGuide, not even an explicit nil
func (o *BRANDDETAIL) UnsetServiceGuide() {
	o.ServiceGuide.Unset()
}

// GetStores returns the Stores field value if set, zero value otherwise.
func (o *BRANDDETAIL) GetStores() []STORESSCHEMA {
	if o == nil || IsNil(o.Stores) {
		var ret []STORESSCHEMA
		return ret
	}
	return o.Stores
}

// GetStoresOk returns a tuple with the Stores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BRANDDETAIL) GetStoresOk() ([]STORESSCHEMA, bool) {
	if o == nil || IsNil(o.Stores) {
		return nil, false
	}
	return o.Stores, true
}

// HasStores returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasStores() bool {
	if o != nil && !IsNil(o.Stores) {
		return true
	}

	return false
}

// SetStores gets a reference to the given []STORESSCHEMA and assigns it to the Stores field.
func (o *BRANDDETAIL) SetStores(v []STORESSCHEMA) {
	o.Stores = v
}

// GetUsageMethods returns the UsageMethods field value if set, zero value otherwise.
func (o *BRANDDETAIL) GetUsageMethods() []USAGEMETHODSCHEMA {
	if o == nil || IsNil(o.UsageMethods) {
		var ret []USAGEMETHODSCHEMA
		return ret
	}
	return o.UsageMethods
}

// GetUsageMethodsOk returns a tuple with the UsageMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BRANDDETAIL) GetUsageMethodsOk() ([]USAGEMETHODSCHEMA, bool) {
	if o == nil || IsNil(o.UsageMethods) {
		return nil, false
	}
	return o.UsageMethods, true
}

// HasUsageMethods returns a boolean if a field has been set.
func (o *BRANDDETAIL) HasUsageMethods() bool {
	if o != nil && !IsNil(o.UsageMethods) {
		return true
	}

	return false
}

// SetUsageMethods gets a reference to the given []USAGEMETHODSCHEMA and assigns it to the UsageMethods field.
func (o *BRANDDETAIL) SetUsageMethods(v []USAGEMETHODSCHEMA) {
	o.UsageMethods = v
}

func (o BRANDDETAIL) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BRANDDETAIL) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BrandId.IsSet() {
		toSerialize["brandId"] = o.BrandId.Get()
	}
	if o.BrandNm.IsSet() {
		toSerialize["brandNm"] = o.BrandNm.Get()
	}
	if o.BrandAddr.IsSet() {
		toSerialize["brandAddr"] = o.BrandAddr.Get()
	}
	if o.BrandLogo.IsSet() {
		toSerialize["brandLogo"] = o.BrandLogo.Get()
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if o.ShortDesc.IsSet() {
		toSerialize["shortDesc"] = o.ShortDesc.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.CategoryID != nil {
		toSerialize["categoryID"] = o.CategoryID
	}
	if o.Order.IsSet() {
		toSerialize["order"] = o.Order.Get()
	}
	if o.ServiceGuide.IsSet() {
		toSerialize["serviceGuide"] = o.ServiceGuide.Get()
	}
	if !IsNil(o.Stores) {
		toSerialize["stores"] = o.Stores
	}
	if !IsNil(o.UsageMethods) {
		toSerialize["usageMethods"] = o.UsageMethods
	}
	return toSerialize, nil
}

type NullableBRANDDETAIL struct {
	value *BRANDDETAIL
	isSet bool
}

func (v NullableBRANDDETAIL) Get() *BRANDDETAIL {
	return v.value
}

func (v *NullableBRANDDETAIL) Set(val *BRANDDETAIL) {
	v.value = val
	v.isSet = true
}

func (v NullableBRANDDETAIL) IsSet() bool {
	return v.isSet
}

func (v *NullableBRANDDETAIL) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBRANDDETAIL(val *BRANDDETAIL) *NullableBRANDDETAIL {
	return &NullableBRANDDETAIL{value: val, isSet: true}
}

func (v NullableBRANDDETAIL) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBRANDDETAIL) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


