/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the VOUCHERVSCHEMA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VOUCHERVSCHEMA{}

// VOUCHERVSCHEMA struct for VOUCHERVSCHEMA
type VOUCHERVSCHEMA struct {
	// TransactionRefId receive from client request
	TransactionRefId NullableString `json:"transactionRefId,omitempty"`
	// Voucher code. Contains 10 numbers, unique and not duplicated with any other voucher. For some brands that do not use Got It code but use integerernal code (Big C, Mobile World), the system returns the integerernal code.
	VoucherCode NullableString `json:"voucherCode,omitempty"`
	// Link of voucher
	VoucherLink NullableString `json:"voucherLink,omitempty"`
	// Last 8 characters of voucher link
	VoucherLinkCode NullableString `json:"voucherLinkCode,omitempty"`
	// Link of voucher image. To display vouchers as images
	VoucherImageLink NullableString `json:"voucherImageLink,omitempty"`
	// Cover link of voucher.
	VoucherCoverLink NullableString `json:"voucherCoverLink,omitempty"`
	// Last 8 characters of voucher cover link
	VoucherCoverLinkCode NullableString `json:"voucherCoverLinkCode,omitempty"`
	// Is a unique code to identify voucher link v and is not valid for use. For example: V1562342ET2
	VoucherSerial NullableString `json:"voucherSerial,omitempty"`
	// Voucher expiration date
	ExpiryDate NullableString `json:"expiryDate,omitempty"`
	Product NullableVOUCHERVSCHEMAProduct `json:"product,omitempty"`
}

// NewVOUCHERVSCHEMA instantiates a new VOUCHERVSCHEMA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVOUCHERVSCHEMA() *VOUCHERVSCHEMA {
	this := VOUCHERVSCHEMA{}
	return &this
}

// NewVOUCHERVSCHEMAWithDefaults instantiates a new VOUCHERVSCHEMA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVOUCHERVSCHEMAWithDefaults() *VOUCHERVSCHEMA {
	this := VOUCHERVSCHEMA{}
	return &this
}

// GetTransactionRefId returns the TransactionRefId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetTransactionRefId() string {
	if o == nil || IsNil(o.TransactionRefId.Get()) {
		var ret string
		return ret
	}
	return *o.TransactionRefId.Get()
}

// GetTransactionRefIdOk returns a tuple with the TransactionRefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetTransactionRefIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionRefId.Get(), o.TransactionRefId.IsSet()
}

// HasTransactionRefId returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasTransactionRefId() bool {
	if o != nil && o.TransactionRefId.IsSet() {
		return true
	}

	return false
}

// SetTransactionRefId gets a reference to the given NullableString and assigns it to the TransactionRefId field.
func (o *VOUCHERVSCHEMA) SetTransactionRefId(v string) {
	o.TransactionRefId.Set(&v)
}
// SetTransactionRefIdNil sets the value for TransactionRefId to be an explicit nil
func (o *VOUCHERVSCHEMA) SetTransactionRefIdNil() {
	o.TransactionRefId.Set(nil)
}

// UnsetTransactionRefId ensures that no value is present for TransactionRefId, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetTransactionRefId() {
	o.TransactionRefId.Unset()
}

// GetVoucherCode returns the VoucherCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherCode() string {
	if o == nil || IsNil(o.VoucherCode.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherCode.Get()
}

// GetVoucherCodeOk returns a tuple with the VoucherCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherCode.Get(), o.VoucherCode.IsSet()
}

// HasVoucherCode returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherCode() bool {
	if o != nil && o.VoucherCode.IsSet() {
		return true
	}

	return false
}

// SetVoucherCode gets a reference to the given NullableString and assigns it to the VoucherCode field.
func (o *VOUCHERVSCHEMA) SetVoucherCode(v string) {
	o.VoucherCode.Set(&v)
}
// SetVoucherCodeNil sets the value for VoucherCode to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherCodeNil() {
	o.VoucherCode.Set(nil)
}

// UnsetVoucherCode ensures that no value is present for VoucherCode, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherCode() {
	o.VoucherCode.Unset()
}

// GetVoucherLink returns the VoucherLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherLink() string {
	if o == nil || IsNil(o.VoucherLink.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherLink.Get()
}

// GetVoucherLinkOk returns a tuple with the VoucherLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherLink.Get(), o.VoucherLink.IsSet()
}

// HasVoucherLink returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherLink() bool {
	if o != nil && o.VoucherLink.IsSet() {
		return true
	}

	return false
}

// SetVoucherLink gets a reference to the given NullableString and assigns it to the VoucherLink field.
func (o *VOUCHERVSCHEMA) SetVoucherLink(v string) {
	o.VoucherLink.Set(&v)
}
// SetVoucherLinkNil sets the value for VoucherLink to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherLinkNil() {
	o.VoucherLink.Set(nil)
}

// UnsetVoucherLink ensures that no value is present for VoucherLink, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherLink() {
	o.VoucherLink.Unset()
}

// GetVoucherLinkCode returns the VoucherLinkCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherLinkCode() string {
	if o == nil || IsNil(o.VoucherLinkCode.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherLinkCode.Get()
}

// GetVoucherLinkCodeOk returns a tuple with the VoucherLinkCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherLinkCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherLinkCode.Get(), o.VoucherLinkCode.IsSet()
}

// HasVoucherLinkCode returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherLinkCode() bool {
	if o != nil && o.VoucherLinkCode.IsSet() {
		return true
	}

	return false
}

// SetVoucherLinkCode gets a reference to the given NullableString and assigns it to the VoucherLinkCode field.
func (o *VOUCHERVSCHEMA) SetVoucherLinkCode(v string) {
	o.VoucherLinkCode.Set(&v)
}
// SetVoucherLinkCodeNil sets the value for VoucherLinkCode to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherLinkCodeNil() {
	o.VoucherLinkCode.Set(nil)
}

// UnsetVoucherLinkCode ensures that no value is present for VoucherLinkCode, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherLinkCode() {
	o.VoucherLinkCode.Unset()
}

// GetVoucherImageLink returns the VoucherImageLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherImageLink() string {
	if o == nil || IsNil(o.VoucherImageLink.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherImageLink.Get()
}

// GetVoucherImageLinkOk returns a tuple with the VoucherImageLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherImageLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherImageLink.Get(), o.VoucherImageLink.IsSet()
}

// HasVoucherImageLink returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherImageLink() bool {
	if o != nil && o.VoucherImageLink.IsSet() {
		return true
	}

	return false
}

// SetVoucherImageLink gets a reference to the given NullableString and assigns it to the VoucherImageLink field.
func (o *VOUCHERVSCHEMA) SetVoucherImageLink(v string) {
	o.VoucherImageLink.Set(&v)
}
// SetVoucherImageLinkNil sets the value for VoucherImageLink to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherImageLinkNil() {
	o.VoucherImageLink.Set(nil)
}

// UnsetVoucherImageLink ensures that no value is present for VoucherImageLink, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherImageLink() {
	o.VoucherImageLink.Unset()
}

// GetVoucherCoverLink returns the VoucherCoverLink field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherCoverLink() string {
	if o == nil || IsNil(o.VoucherCoverLink.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherCoverLink.Get()
}

// GetVoucherCoverLinkOk returns a tuple with the VoucherCoverLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherCoverLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherCoverLink.Get(), o.VoucherCoverLink.IsSet()
}

// HasVoucherCoverLink returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherCoverLink() bool {
	if o != nil && o.VoucherCoverLink.IsSet() {
		return true
	}

	return false
}

// SetVoucherCoverLink gets a reference to the given NullableString and assigns it to the VoucherCoverLink field.
func (o *VOUCHERVSCHEMA) SetVoucherCoverLink(v string) {
	o.VoucherCoverLink.Set(&v)
}
// SetVoucherCoverLinkNil sets the value for VoucherCoverLink to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherCoverLinkNil() {
	o.VoucherCoverLink.Set(nil)
}

// UnsetVoucherCoverLink ensures that no value is present for VoucherCoverLink, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherCoverLink() {
	o.VoucherCoverLink.Unset()
}

// GetVoucherCoverLinkCode returns the VoucherCoverLinkCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherCoverLinkCode() string {
	if o == nil || IsNil(o.VoucherCoverLinkCode.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherCoverLinkCode.Get()
}

// GetVoucherCoverLinkCodeOk returns a tuple with the VoucherCoverLinkCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherCoverLinkCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherCoverLinkCode.Get(), o.VoucherCoverLinkCode.IsSet()
}

// HasVoucherCoverLinkCode returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherCoverLinkCode() bool {
	if o != nil && o.VoucherCoverLinkCode.IsSet() {
		return true
	}

	return false
}

// SetVoucherCoverLinkCode gets a reference to the given NullableString and assigns it to the VoucherCoverLinkCode field.
func (o *VOUCHERVSCHEMA) SetVoucherCoverLinkCode(v string) {
	o.VoucherCoverLinkCode.Set(&v)
}
// SetVoucherCoverLinkCodeNil sets the value for VoucherCoverLinkCode to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherCoverLinkCodeNil() {
	o.VoucherCoverLinkCode.Set(nil)
}

// UnsetVoucherCoverLinkCode ensures that no value is present for VoucherCoverLinkCode, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherCoverLinkCode() {
	o.VoucherCoverLinkCode.Unset()
}

// GetVoucherSerial returns the VoucherSerial field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetVoucherSerial() string {
	if o == nil || IsNil(o.VoucherSerial.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherSerial.Get()
}

// GetVoucherSerialOk returns a tuple with the VoucherSerial field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetVoucherSerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherSerial.Get(), o.VoucherSerial.IsSet()
}

// HasVoucherSerial returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasVoucherSerial() bool {
	if o != nil && o.VoucherSerial.IsSet() {
		return true
	}

	return false
}

// SetVoucherSerial gets a reference to the given NullableString and assigns it to the VoucherSerial field.
func (o *VOUCHERVSCHEMA) SetVoucherSerial(v string) {
	o.VoucherSerial.Set(&v)
}
// SetVoucherSerialNil sets the value for VoucherSerial to be an explicit nil
func (o *VOUCHERVSCHEMA) SetVoucherSerialNil() {
	o.VoucherSerial.Set(nil)
}

// UnsetVoucherSerial ensures that no value is present for VoucherSerial, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetVoucherSerial() {
	o.VoucherSerial.Unset()
}

// GetExpiryDate returns the ExpiryDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetExpiryDate() string {
	if o == nil || IsNil(o.ExpiryDate.Get()) {
		var ret string
		return ret
	}
	return *o.ExpiryDate.Get()
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetExpiryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiryDate.Get(), o.ExpiryDate.IsSet()
}

// HasExpiryDate returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasExpiryDate() bool {
	if o != nil && o.ExpiryDate.IsSet() {
		return true
	}

	return false
}

// SetExpiryDate gets a reference to the given NullableString and assigns it to the ExpiryDate field.
func (o *VOUCHERVSCHEMA) SetExpiryDate(v string) {
	o.ExpiryDate.Set(&v)
}
// SetExpiryDateNil sets the value for ExpiryDate to be an explicit nil
func (o *VOUCHERVSCHEMA) SetExpiryDateNil() {
	o.ExpiryDate.Set(nil)
}

// UnsetExpiryDate ensures that no value is present for ExpiryDate, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetExpiryDate() {
	o.ExpiryDate.Unset()
}

// GetProduct returns the Product field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERVSCHEMA) GetProduct() VOUCHERVSCHEMAProduct {
	if o == nil || IsNil(o.Product.Get()) {
		var ret VOUCHERVSCHEMAProduct
		return ret
	}
	return *o.Product.Get()
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERVSCHEMA) GetProductOk() (*VOUCHERVSCHEMAProduct, bool) {
	if o == nil {
		return nil, false
	}
	return o.Product.Get(), o.Product.IsSet()
}

// HasProduct returns a boolean if a field has been set.
func (o *VOUCHERVSCHEMA) HasProduct() bool {
	if o != nil && o.Product.IsSet() {
		return true
	}

	return false
}

// SetProduct gets a reference to the given NullableVOUCHERVSCHEMAProduct and assigns it to the Product field.
func (o *VOUCHERVSCHEMA) SetProduct(v VOUCHERVSCHEMAProduct) {
	o.Product.Set(&v)
}
// SetProductNil sets the value for Product to be an explicit nil
func (o *VOUCHERVSCHEMA) SetProductNil() {
	o.Product.Set(nil)
}

// UnsetProduct ensures that no value is present for Product, not even an explicit nil
func (o *VOUCHERVSCHEMA) UnsetProduct() {
	o.Product.Unset()
}

func (o VOUCHERVSCHEMA) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VOUCHERVSCHEMA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.TransactionRefId.IsSet() {
		toSerialize["transactionRefId"] = o.TransactionRefId.Get()
	}
	if o.VoucherCode.IsSet() {
		toSerialize["voucherCode"] = o.VoucherCode.Get()
	}
	if o.VoucherLink.IsSet() {
		toSerialize["voucherLink"] = o.VoucherLink.Get()
	}
	if o.VoucherLinkCode.IsSet() {
		toSerialize["voucherLinkCode"] = o.VoucherLinkCode.Get()
	}
	if o.VoucherImageLink.IsSet() {
		toSerialize["voucherImageLink"] = o.VoucherImageLink.Get()
	}
	if o.VoucherCoverLink.IsSet() {
		toSerialize["voucherCoverLink"] = o.VoucherCoverLink.Get()
	}
	if o.VoucherCoverLinkCode.IsSet() {
		toSerialize["voucherCoverLinkCode"] = o.VoucherCoverLinkCode.Get()
	}
	if o.VoucherSerial.IsSet() {
		toSerialize["voucherSerial"] = o.VoucherSerial.Get()
	}
	if o.ExpiryDate.IsSet() {
		toSerialize["expiryDate"] = o.ExpiryDate.Get()
	}
	if o.Product.IsSet() {
		toSerialize["product"] = o.Product.Get()
	}
	return toSerialize, nil
}

type NullableVOUCHERVSCHEMA struct {
	value *VOUCHERVSCHEMA
	isSet bool
}

func (v NullableVOUCHERVSCHEMA) Get() *VOUCHERVSCHEMA {
	return v.value
}

func (v *NullableVOUCHERVSCHEMA) Set(val *VOUCHERVSCHEMA) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERVSCHEMA) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERVSCHEMA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERVSCHEMA(val *VOUCHERVSCHEMA) *NullableVOUCHERVSCHEMA {
	return &NullableVOUCHERVSCHEMA{value: val, isSet: true}
}

func (v NullableVOUCHERVSCHEMA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERVSCHEMA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


