/*
Sample API

Technical document APIs for API Version 4.

API version: 4.0.0
Contact: quang.huynh@gotit.vn
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gotit_api_go_sdk

import (
	"encoding/json"
)

// checks if the VOUCHERSENDEMAILSCHEMA type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VOUCHERSENDEMAILSCHEMA{}

// VOUCHERSENDEMAILSCHEMA struct for VOUCHERSENDEMAILSCHEMA
type VOUCHERSENDEMAILSCHEMA struct {
	// Last 8 characters of voucher link
	VoucherLinkCode NullableString `json:"voucherLinkCode,omitempty"`
	// Email of user receive voucher
	Email NullableString `json:"email,omitempty"`
	// Email of user receive voucher
	ReceiverNm NullableString `json:"receiverNm,omitempty"`
	// Name of sender
	SenderNm NullableString `json:"senderNm,omitempty"`
	// Message send
	Message NullableString `json:"message,omitempty"`
}

// NewVOUCHERSENDEMAILSCHEMA instantiates a new VOUCHERSENDEMAILSCHEMA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVOUCHERSENDEMAILSCHEMA() *VOUCHERSENDEMAILSCHEMA {
	this := VOUCHERSENDEMAILSCHEMA{}
	return &this
}

// NewVOUCHERSENDEMAILSCHEMAWithDefaults instantiates a new VOUCHERSENDEMAILSCHEMA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVOUCHERSENDEMAILSCHEMAWithDefaults() *VOUCHERSENDEMAILSCHEMA {
	this := VOUCHERSENDEMAILSCHEMA{}
	return &this
}

// GetVoucherLinkCode returns the VoucherLinkCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDEMAILSCHEMA) GetVoucherLinkCode() string {
	if o == nil || IsNil(o.VoucherLinkCode.Get()) {
		var ret string
		return ret
	}
	return *o.VoucherLinkCode.Get()
}

// GetVoucherLinkCodeOk returns a tuple with the VoucherLinkCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDEMAILSCHEMA) GetVoucherLinkCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VoucherLinkCode.Get(), o.VoucherLinkCode.IsSet()
}

// HasVoucherLinkCode returns a boolean if a field has been set.
func (o *VOUCHERSENDEMAILSCHEMA) HasVoucherLinkCode() bool {
	if o != nil && o.VoucherLinkCode.IsSet() {
		return true
	}

	return false
}

// SetVoucherLinkCode gets a reference to the given NullableString and assigns it to the VoucherLinkCode field.
func (o *VOUCHERSENDEMAILSCHEMA) SetVoucherLinkCode(v string) {
	o.VoucherLinkCode.Set(&v)
}
// SetVoucherLinkCodeNil sets the value for VoucherLinkCode to be an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) SetVoucherLinkCodeNil() {
	o.VoucherLinkCode.Set(nil)
}

// UnsetVoucherLinkCode ensures that no value is present for VoucherLinkCode, not even an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) UnsetVoucherLinkCode() {
	o.VoucherLinkCode.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDEMAILSCHEMA) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDEMAILSCHEMA) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *VOUCHERSENDEMAILSCHEMA) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *VOUCHERSENDEMAILSCHEMA) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) UnsetEmail() {
	o.Email.Unset()
}

// GetReceiverNm returns the ReceiverNm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDEMAILSCHEMA) GetReceiverNm() string {
	if o == nil || IsNil(o.ReceiverNm.Get()) {
		var ret string
		return ret
	}
	return *o.ReceiverNm.Get()
}

// GetReceiverNmOk returns a tuple with the ReceiverNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDEMAILSCHEMA) GetReceiverNmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReceiverNm.Get(), o.ReceiverNm.IsSet()
}

// HasReceiverNm returns a boolean if a field has been set.
func (o *VOUCHERSENDEMAILSCHEMA) HasReceiverNm() bool {
	if o != nil && o.ReceiverNm.IsSet() {
		return true
	}

	return false
}

// SetReceiverNm gets a reference to the given NullableString and assigns it to the ReceiverNm field.
func (o *VOUCHERSENDEMAILSCHEMA) SetReceiverNm(v string) {
	o.ReceiverNm.Set(&v)
}
// SetReceiverNmNil sets the value for ReceiverNm to be an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) SetReceiverNmNil() {
	o.ReceiverNm.Set(nil)
}

// UnsetReceiverNm ensures that no value is present for ReceiverNm, not even an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) UnsetReceiverNm() {
	o.ReceiverNm.Unset()
}

// GetSenderNm returns the SenderNm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDEMAILSCHEMA) GetSenderNm() string {
	if o == nil || IsNil(o.SenderNm.Get()) {
		var ret string
		return ret
	}
	return *o.SenderNm.Get()
}

// GetSenderNmOk returns a tuple with the SenderNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDEMAILSCHEMA) GetSenderNmOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SenderNm.Get(), o.SenderNm.IsSet()
}

// HasSenderNm returns a boolean if a field has been set.
func (o *VOUCHERSENDEMAILSCHEMA) HasSenderNm() bool {
	if o != nil && o.SenderNm.IsSet() {
		return true
	}

	return false
}

// SetSenderNm gets a reference to the given NullableString and assigns it to the SenderNm field.
func (o *VOUCHERSENDEMAILSCHEMA) SetSenderNm(v string) {
	o.SenderNm.Set(&v)
}
// SetSenderNmNil sets the value for SenderNm to be an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) SetSenderNmNil() {
	o.SenderNm.Set(nil)
}

// UnsetSenderNm ensures that no value is present for SenderNm, not even an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) UnsetSenderNm() {
	o.SenderNm.Unset()
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VOUCHERSENDEMAILSCHEMA) GetMessage() string {
	if o == nil || IsNil(o.Message.Get()) {
		var ret string
		return ret
	}
	return *o.Message.Get()
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VOUCHERSENDEMAILSCHEMA) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Message.Get(), o.Message.IsSet()
}

// HasMessage returns a boolean if a field has been set.
func (o *VOUCHERSENDEMAILSCHEMA) HasMessage() bool {
	if o != nil && o.Message.IsSet() {
		return true
	}

	return false
}

// SetMessage gets a reference to the given NullableString and assigns it to the Message field.
func (o *VOUCHERSENDEMAILSCHEMA) SetMessage(v string) {
	o.Message.Set(&v)
}
// SetMessageNil sets the value for Message to be an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) SetMessageNil() {
	o.Message.Set(nil)
}

// UnsetMessage ensures that no value is present for Message, not even an explicit nil
func (o *VOUCHERSENDEMAILSCHEMA) UnsetMessage() {
	o.Message.Unset()
}

func (o VOUCHERSENDEMAILSCHEMA) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VOUCHERSENDEMAILSCHEMA) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.VoucherLinkCode.IsSet() {
		toSerialize["voucherLinkCode"] = o.VoucherLinkCode.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.ReceiverNm.IsSet() {
		toSerialize["receiverNm"] = o.ReceiverNm.Get()
	}
	if o.SenderNm.IsSet() {
		toSerialize["senderNm"] = o.SenderNm.Get()
	}
	if o.Message.IsSet() {
		toSerialize["message"] = o.Message.Get()
	}
	return toSerialize, nil
}

type NullableVOUCHERSENDEMAILSCHEMA struct {
	value *VOUCHERSENDEMAILSCHEMA
	isSet bool
}

func (v NullableVOUCHERSENDEMAILSCHEMA) Get() *VOUCHERSENDEMAILSCHEMA {
	return v.value
}

func (v *NullableVOUCHERSENDEMAILSCHEMA) Set(val *VOUCHERSENDEMAILSCHEMA) {
	v.value = val
	v.isSet = true
}

func (v NullableVOUCHERSENDEMAILSCHEMA) IsSet() bool {
	return v.isSet
}

func (v *NullableVOUCHERSENDEMAILSCHEMA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVOUCHERSENDEMAILSCHEMA(val *VOUCHERSENDEMAILSCHEMA) *NullableVOUCHERSENDEMAILSCHEMA {
	return &NullableVOUCHERSENDEMAILSCHEMA{value: val, isSet: true}
}

func (v NullableVOUCHERSENDEMAILSCHEMA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVOUCHERSENDEMAILSCHEMA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


